{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "utils",
    "version": "0.11.3-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "utils-0.11.3-SNAPSHOT.jar",
          "url": "utils-0.11.3-SNAPSHOT.jar",
          "size": 45164,
          "sha512": "8f06f7b65e1a786b96da2b213eda68c79f393512e93970edea8165da3eee2b4541d491797a64b57f8770c14bdcaa69b6e84eb8ee7208bce62db6071348925e29",
          "sha256": "83ceee5fc71d501183c6e74dfdd035f62fd63667e26479d0d2e77da1dc29d65c",
          "sha1": "c4ae0736a859a6fcaef35c4ed8cc09126393e2d4",
          "md5": "8ea58de32e2daef4c70c53cad06d3e1b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.openjson",
          "module": "openjson",
          "version": {
            "requires": "1.0.13"
          }
        }
      ],
      "files": [
        {
          "name": "utils-0.11.3-SNAPSHOT.jar",
          "url": "utils-0.11.3-SNAPSHOT.jar",
          "size": 45164,
          "sha512": "8f06f7b65e1a786b96da2b213eda68c79f393512e93970edea8165da3eee2b4541d491797a64b57f8770c14bdcaa69b6e84eb8ee7208bce62db6071348925e29",
          "sha256": "83ceee5fc71d501183c6e74dfdd035f62fd63667e26479d0d2e77da1dc29d65c",
          "sha1": "c4ae0736a859a6fcaef35c4ed8cc09126393e2d4",
          "md5": "8ea58de32e2daef4c70c53cad06d3e1b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.11.3-SNAPSHOT-javadoc.jar",
          "url": "utils-0.11.3-SNAPSHOT-javadoc.jar",
          "size": 175080,
          "sha512": "e505e17f53fe37f30905654aef00674cf65ee2f7ddbf95fa360302d6dab247b42f4efe091be49a4bb33821f07b0463bf1a38544f87f46686f6841e027001f392",
          "sha256": "365879255b018fc65397d4c4eb276151484db019f5e5cc8ebf9261d069ae05d5",
          "sha1": "3daca2e333ddd2b91c3f71f24afdfb04db143fbc",
          "md5": "53815b09fe04ab00f5b780a832f56287"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utils-0.11.3-SNAPSHOT-sources.jar",
          "url": "utils-0.11.3-SNAPSHOT-sources.jar",
          "size": 49085,
          "sha512": "420288a29f94486a96ab5ca2ce5107619c5b429b1ffa0c6735e52e0a63f42fef65af4a47f64d9954753aa2845cb254602e018c8c0d17e8e740cc6bdcc5a50761",
          "sha256": "91ca627944985caca24cd565eb44a719bd112565e1d6f2c7df5018ee5e055f1d",
          "sha1": "65d0bc89f88b4525c6052962070175d6bd05eaa0",
          "md5": "cc78aef746f2edc5aec4a2d4fbb8097a"
        }
      ]
    }
  ]
}
