{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "native-maven-plugin",
    "version": "0.11.5-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-maven-plugin-0.11.5-SNAPSHOT.jar",
          "url": "native-maven-plugin-0.11.5-SNAPSHOT.jar",
          "size": 124070,
          "sha512": "c7a83ac0e8064cd2727da995de86a474ca3082c0c981ef44259a5123fab54cf23a54ecffd1962609a9d606d2b5c23d78ad17481d5745daade3d0a3582befb0bc",
          "sha256": "dd50d95fb55b2bbfe6d0ec26f28d81dfb053d18ce72f0c1adbbe0bfc651ac640",
          "sha1": "e252eefa34e71f43e475d8b9173a46b11be06d65",
          "md5": "00996ecff498e6fcb77ffb9837ae4e12"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.graalvm.buildtools",
          "module": "utils",
          "version": {
            "requires": "0.11.5-SNAPSHOT"
          }
        },
        {
          "group": "com.github.openjson",
          "module": "openjson",
          "version": {
            "requires": "1.0.13"
          }
        },
        {
          "group": "org.graalvm.buildtools",
          "module": "graalvm-reachability-metadata",
          "version": {
            "requires": "0.11.5-SNAPSHOT"
          }
        },
        {
          "group": "org.cyclonedx",
          "module": "cyclonedx-maven-plugin",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "native-maven-plugin-0.11.5-SNAPSHOT.jar",
          "url": "native-maven-plugin-0.11.5-SNAPSHOT.jar",
          "size": 124070,
          "sha512": "c7a83ac0e8064cd2727da995de86a474ca3082c0c981ef44259a5123fab54cf23a54ecffd1962609a9d606d2b5c23d78ad17481d5745daade3d0a3582befb0bc",
          "sha256": "dd50d95fb55b2bbfe6d0ec26f28d81dfb053d18ce72f0c1adbbe0bfc651ac640",
          "sha1": "e252eefa34e71f43e475d8b9173a46b11be06d65",
          "md5": "00996ecff498e6fcb77ffb9837ae4e12"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-maven-plugin-0.11.5-SNAPSHOT-javadoc.jar",
          "url": "native-maven-plugin-0.11.5-SNAPSHOT-javadoc.jar",
          "size": 203695,
          "sha512": "3d9a023015b5a51f3fa148eefe26f0e5d3d3991ebc50a0c4b09bd0e013a0232f5893e067062dc798d98aa69ddb12f5bf1e61caa3f0fc9fa903235b71a4953d97",
          "sha256": "2b51202784f10c0a886c6fe70846d2cc6ba12d36023c113dbcea03ef0aa0613b",
          "sha1": "dd4a255d516e794d22d518257334197b2fa47914",
          "md5": "8c2df83ef2da7803e09171f8622b58d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-maven-plugin-0.11.5-SNAPSHOT-sources.jar",
          "url": "native-maven-plugin-0.11.5-SNAPSHOT-sources.jar",
          "size": 89901,
          "sha512": "f1e926d66e282e9d3e04d5662021361356050ee752fd44c0a48e8636e98fc7c62d7a337074947e7f4e7d817e86dbe195e559f46a1ce2da7cdf2c6b607399e10b",
          "sha256": "96b27d1e8c7fde728cef95b86e0c3e03b6e95c778425313a5fbda26d00d7f7a5",
          "sha1": "c932da303c306c1b8f24d25a27509e843245c838",
          "md5": "2c4765ca378f093e4979eb51bb53ad9c"
        }
      ]
    }
  ]
}
