= Building Native Images with Gradle: An End-to-End Guide
The GraalVM team
:highlighjsdir: {gradle-relative-srcdir}/highlight

This guide walks you through integrating the Gradle plugin for Native Image into your project.
It starts from enabling the plugin, building the first native image, and running it.

Then it takes you to more advanced use-cases such as plugin's configuration, applying optimizations, running native tests, and troubleshooting.
If you are an advanced user, you can skip the getting started part and go directly to the advanced section.

[[getting-started]]
== Getting Started
To compile your application ahead of time with https://www.graalvm.org/latest/reference-manual/native-image/[GraalVM Native Image] and Gradle, enable the Gradle plugin for Native Image building.
The plugin requires that you https://www.graalvm.org/downloads/[install GraalVM].

[NOTE]
====
A JDK version between 17 and 21 is required to execute Gradle (see the https://docs.gradle.org/current/userguide/compatibility.html[Gradle Compatibility Matrix]).
====

[[add-plugin]]
=== Add the Plugin

- Add the plugin declaration to your _build.gradle_ / _build.gradle.kts_ file inside the `plugins` block:

[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
  id 'org.graalvm.buildtools.native' version '{gradle-plugin-version}'
----

[source,kotlin,subs="verbatim,attributes",role="multi-language-sample"]
----
  id("org.graalvm.buildtools.native") version "{gradle-plugin-version}"
----

All plugin versions are listed https://github.com/graalvm/native-build-tools/releases[here]

[[run-your-project]]
=== Build and Run Your Application

This plugin works with the `application` plugin and registers a number of tasks and extensions for you to configure.

- Build a native executable of your application.
This command will compile your application and create a native executable in the _build/native/nativeCompile/_ directory:

[source,bash,role="multi-language-sample"]
----
./gradlew nativeCompile
----

- Run the application from the native executable:

[source,bash,role="multi-language-sample"]
----
./gradlew nativeRun
----

Continue reading below to learn more about the plugin.

[[advanced-use-cases]]
== Advanced Use Cases: How to

For advanced use cases, this guide provides instructions for configuring the build process, running tests on native code, gathering execution profiles, troubleshooting missing configuration, and enabling diagnostic tools to analyze native images.

[[configure-image-build]]
=== Configure Native Image Build

The plugin supports passing options directly to Native Image inside the `graalvmNative` block in the _build.gradle_ / _build.gradle.kts_ file.
Using `buildArgs.add("<option>")`, you can pass any Native Image build option listed on https://www.graalvm.org/reference-manual/native-image/overview/Options/[this page].
You can pass options to <<gradle-plugin.adoc#configure-native-image,configure the `main` or the `test` native binary>>, or both at the same time.

The plugin also provides special properties to configure the build:

- `mainClass` - Provides the main class to use, defaults to the `application.mainClass`
- `imageName` - Specifies the name for the native executable file. If a custom name is not supplied, the artifact ID of the project will be used by default (defaults to the project name).
- `jvmArgs` - Passes the given argument directly to the JVM running the `native-image` tool
- `quickBuild` - Enables quick build mode
- `verbose` - Enables the verbose output
- and many more <<gradle-plugin.adoc#native-image-options,listed here>>.

Here is an example of additional options usage:

[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        // common options
        verbose = true
    }

    binaries.main {
        // options to configure the main binary
        imageName = 'myApp'
        mainClass = 'org.example.Main'
        buildArgs.add('-O3') // enables additional compiler optimizations
    }

    binaries.test {
        // options to configure the test binary
        quickBuild = true
        debug = true
    }
}
----

[source,kotlin,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        // common options
        verbose.set(true)
    }

    binaries.main {
        // options to configure the main binary
        imageName.set('application')
        mainClass.set('org.example.Main')
        buildArgs.add('-O3')  // enables additional compiler optimizations
    }

    binaries.test {
        // options to configure the test binary
        quickBuild.set(true)
        debug.set(true)
    }
}
----

[TIP]
====
As an alternative, you can pass additional build options via the `NATIVE_IMAGE_OPTIONS` environment variable, on the command line.
This works similarly to `JAVA_TOOL_OPTIONS`, where the value of the environment variable is prefixed to the options supplied to `native-image`.
====

Learn more about Native Image build configuration https://www.graalvm.org/reference-manual/native-image/overview/BuildConfiguration/[on the website].

[[run-junit-tests]]
=== Run Junit Tests

This plugin supports running tests on the JUnit Platform.
The tests are compiled ahead of time and executed as native code.

- Add the JUnit 5 dependency to _build.gradle_ / _build.gradle.kts_ to include the testing framework:

[source,groovy,role="multi-language-sample"]
----
testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
testImplementation 'junit:junit:4.13.2'
----

[source,kotlin,role="multi-language-sample"]
----
testImplementation('org.junit.jupiter:junit-jupiter-api:5.8.1')
testRuntimeOnly('org.junit.jupiter:junit-jupiter-engine:5.8.1')
testImplementation('junit:junit:4.13.2')
----

- Run the tests:

[source,bash,role="multi-language-sample"]
----
./gradlew nativeTest
----

The tests are compiled ahead of time and executed as native code.

[[gather-execution-profiles]]
=== Gather Execution Profiles and Build Optimized Images

You may want to gather profiling information from your application's execution to pinpoint areas of inefficiency.
With this profiling data, you can also build an optimized native image.

The technique for building native images optimized on profiles is called https://www.graalvm.org/latest/reference-manual/native-image/optimizations-and-performance/PGO/[Profile-Guided Optimization (PGO)].
With PGO you can “train” your native application for specific workloads to improve performance and throughput.
The PGO workflow includes three steps.

[NOTE]
====
PGO is available in Oracle GraalVM.
====

Step 1: **Build an instrumented native image** by passing the `--pgo-instrument` option directly to the compile command:

[source,bash, role="multi-language-sample"]
----
./gradlew nativeCompile --pgo-instrument
----

This generates a native executable under _build/native/nativeCompile_ with the _-instrumented_ suffix.

Step 2: **Gather profiles** by running the instrumented executable.
By default, the _default.iprof_ file, if not specified otherwise, is generated alongside the native executable.

[source,bash, role="multi-language-sample"]
----
./build/native/nativeCompile/application-instrumented
----

Step 3. **Build an optimized native image with profiles**.
This step involves copying the generated profile to the conventional directory, ensuring it is automatically used during the build process.
Place the _default.iprof_ file in the _src/pgo-profiles/main_ directory, and then run:

[source,bash, role="multi-language-sample"]
----
./gradlew nativeCompile
----

If everything was done properly, you will see _"PGO: user-provided"_ in the native image build output.
Once the optimized image is built, run it:

[source,bash, role="multi-language-sample"]
----
./gradlew nativeRun
----

The application's performance when running from this native executable should be comparable to, or even faster than, running on the JVM.
Learn more about PGO https://www.graalvm.org/reference-manual/native-image/optimizations-and-performance/PGO/basic-usage[on the website].

[[troubleshoot-missing-configuration]]
=== Troubleshoot Missing Configuration

[[detect-missing-metadata]]
==== Detect Missing Metadata

Quite possibly, your application relies on external libraries.
If your application uses a well-supported framework such as Spring or Micronaut, its dependencies should be compatible with Native Image.
Frameworks and libraries that support Native Image by default provide configurations in the https://github.com/oracle/graalvm-reachability-metadata[GraalVM Reachability Metadata Repository].
When you build a native image, Native Build Tools reference this repository to apply the required configuration automatically.

[TIP]
====
You can find an extensive list of libraries and frameworks from the Java ecosystem tested with Native Image on https://www.graalvm.org/native-image/libraries-and-frameworks/[this page].
====

However, it may happen, that your native image crashes at run time with a missing class or resource.
To address this, start by checking if any required configuration is missing.

The best way to detect missing metadata is by running your native tests.
Alternatively, you can **identify missing configuration manually** using the following method.

- Pass the `--exact-reachability-metadata` option to the `native-image` tool inside `graalvmNative` block of your _build.gradle_, as shown below:

[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        buildArgs.add('--exact-reachability-metadata')
        runtimeArgs.add('-XX:MissingRegistrationReportingMode=Warn')
    }
}
----

[source,kotlin,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        buildArgs.add('--exact-reachability-metadata')
        runtimeArgs.add('-XX:MissingRegistrationReportingMode=Warn')
    }
}
----

[NOTE]
====
The `--exact-reachability-metadata` option was introduced in GraalVM for JDK 23. With older versions, use `-H:ThrowMissingRegistrationErrors=` instead.
====

- Rebuild and re-run the application:

[source,bash, role="multi-language-sample"]
----
./gradlew nativeRun
----

- If there is any missing metadata printed to the console, **add it to the configuration file manually**, as described https://www.graalvm.org/reference-manual/native-image/metadata/#specifying-metadata-with-json[here], or **collect it automatically using the Tracing agent**.
(See next.)

- Rebuild your native image and test again.

[[collect-metadata]]
==== Collect Metadata Automatically with Tracing Agent

Your application may use dynamic Java features such as reflection, serialization, or resource loading.
It is also possible that a framework your application relies on uses a library dependency incompatible with Native Image.
In such cases, additional metadata is required.

The easiest way to collect this metadata is by using the https://www.graalvm.org/reference-manual/native-image/metadata/AutomaticMetadataCollection/[Tracing Agent].
This agent tracks all usages of dynamic features during application execution on the JVM and generates the necessary configuration.

The agent is disabled by default.
You can enable it on the command line or inside the `graalvmNative` block in _build.gradle_ / _build.gradle.kts_.

To enable the agent via the command line, pass the `-Pagent` option when running Gradle:

[source,bash, role="multi-language-sample"]
----
./gradlew -Pagent run
----

[NOTE]
====
Enabling the agent via the command line only attaches it for a specific run; it does not automatically run every time you build the application.
====

To enable the agent inside the build configuration and collect missing metadata, do the following.

Step 1: **Enable the agent** by setting `agent` to `true` in the `graalvmNative` block:

[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    agent {
        enabled = true
    }
}
----

[source,kotlin,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    agent {
        enabled.set(true)
    }
}
----

From that point on, commands such as `run` or `test` will execute with the agent attached.
For example you can execute the following command and the agent will be attached automatically:

[source,bash, role="multi-language-sample"]
----
./gradlew run
----

By default, the agent creates the metadata in the _build/native/agent-output_ directory.

Step 2: **Copy the generated metadata** from the default location, _build/native/agent-output_, to the resources directory, for example, _resources/META-INF/native-image_.
Native Image automatically uses the metadata from this location.

To do that with Gradle, configure and run the `metadataCopy` task.

Add a new task named `metadataCopy` inside the `graalvmNative` block.
Your `agent` configuration should look like this:

[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
agent {
    enabled = true
    metadataCopy {
        inputTaskNames.add("run")
        outputDirectories.add("src/main/resources/META-INF/native-image/org.example")
        mergeWithExisting = true
    }
}
----

[source,kotlin,subs="verbatim,attributes", role="multi-language-sample"]
----
agent {
    enabled.set(true)
    metadataCopy {
        inputTaskNames.add("run")
        outputDirectories.add("src/main/resources/META-INF/native-image/org.example")
        mergeWithExisting.set(true)
    }
}
----

In this block:

- `inputTaskNames` - specifies tasks previously executed with the agent attached (tasks that generated metadata in the last step)
- `outputDirectories` - specifies the location where you want to copy the generated metadata
- `mergeWithExisting` - specifies whether the metadata you want to copy should be merged with the metadata that already exists on the give location, or not. This only makes sense when there is already some existing metadata, created before.

Step 3: Now that the `metadataCopy` task is configured, **run the metadataCopy task**:

[source,bash,subs="verbatim,attributes", role="multi-language-sample"]
----
./gradlew metadataCopy
----

Step 4: Finally, **build the native image with the metadata**:

[source,bash, role="multi-language-sample"]
----
./gradlew nativeCompile
----

Run it:

[source,bash, role="multi-language-sample"]
----
./gradlew nativeRun
----

If your native image is successfully build, but still fails at run time, check the troubleshooting guide https://www.graalvm.org/reference-manual/native-image/guides/troubleshoot-run-time-errors/[Troubleshoot Native Image Run-Time Errors].

Learn more about how to fine-tune the agent further <<gradle-plugin.adoc#native-image-tracing-agent,here>>.

[[use-diagnostics-tools]]
=== Use Diagnostics Tools

If you need to diagnose the native applications you build, or monitor your Java application when launched from a native executable, Native Image offers tools for debugging and analyzing the produced binary.
For example:

[source,groovy, role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        buildArgs.add('--emit build-report')
        buildArgs.add('--enable-monitoring=jfr')
        debug = true
    }
}
----

[source,kotlin, role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        buildArgs.add('--emit build-report')
        buildArgs.add('--enable-monitoring=jfr')
        debug.set(true)
    }
}
----

- The `--emit build-report` option generates an HTML page report alongside the native executable that you can open in a browser.
It provides broad information about each build stage as well as the generated binary’s contents.
You can read more about Build Report features https://www.graalvm.org/latest/reference-manual/native-image/overview/build-report/[here].

[NOTE]
====
Build Report is available in Oracle GraalVM.
When running on GraalVM for JDK 21, pass the `-H:+BuildReport` option instead to generate a build report.
====

- The `--enable-monitoring=jfr` instructs the plugin to https://www.graalvm.org/reference-manual/native-image/guides/build-and-run-native-executable-with-jfr/[build a native executable with the JDK Flight Recorder (JFR) support].

- The `<debug>` option generates a native executable with debug information for https://www.graalvm.org/reference-manual/native-image/guides/debug-native-image-process/[source-level debugging with the GNU Debugger (GDB)].

All the monitoring and debugging tools https://www.graalvm.org/reference-manual/native-image/debugging-and-diagnostics/[listed on the website], can be enabled in the plugin configuration using `buildArgs`.

=== Learn more

To continue learning, refer to the <<changelog.adoc#,extensive reference documentation for the GraalVM Native Image Gradle plugin>>.
