= End-to-end Native Maven Plugin guide
The GraalVM team
:highlighjsdir: {maven-relative-srcdir}/highlight

This guide walks you through integrating the Gradle plugin for Native Image into your project.
It starts from enabling the plugin, building the first native image, and running it.

Then it takes you to more advanced use-cases such us providing configuration.
If you are an advanced user, you can skip the getting started part and go directly to the advanced section.

[[getting-started]]
== Getting started
To compile your application ahead of time with https://www.graalvm.org/latest/reference-manual/native-image/[GraalVM Native Image] and Maven, enable the Maven plugin for Native Image building.

The plugin requires that you https://www.graalvm.org/downloads/[install GraalVM].

[[adding-plugin]]
=== Adding the GraalVM Native Plugin

- Add the following block into your `pom.xml` file:

[source,xml, role="multi-language-sample"]
----
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>{maven-plugin-version}</version>
    <extensions>true</extensions>
    <executions>
      <execution>
        <id>build-native</id>
        <goals>
          <goal>compile-no-fork</goal>
        </goals>
        <phase>package</phase>
      </execution>
      <execution>
        <id>test-native</id>
        <goals>
          <goal>test</goal>
        </goals>
        <phase>test</phase>
      </execution>
    </executions>
    <configuration>
        <mainClass>org.example.Main</mainClass>
    </configuration>
</plugin>
----

For convenience, you can create a maven profile and add plugin into it:

[source,xml, role="multi-language-sample"]
----
<profiles>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>{maven-plugin-version}</version>
            <extensions>true</extensions>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>compile-no-fork</goal>
                </goals>
                <phase>package</phase>
              </execution>
              <execution>
                <id>test-native</id>
                <goals>
                  <goal>test</goal>
                </goals>
                <phase>test</phase>
              </execution>
            </executions>
            <configuration>
              <mainClass>org.example.Main</mainClass>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
</profiles>
----

Older versions of the plugin are listed https://github.com/graalvm/native-build-tools/releases[here].

- You can configure the plugin inside the `<configuration>` tag like following:

[source,xml, role="multi-language-sample"]
----
<configuration>
  <imageName>example-app</imageName>
  <mainClass>org.example.Main</mainClass>
  <buildArgs>
      <buildArg>-Ob</buildArg> <!-- for optimized build use -O3 -->
  </buildArgs>
</configuration>
----

It specifies the path for the application main class (the main entry point) and the name for a native executable file.
Adjust this path according to your application sources.

You can pass additional options to the Native Image tool using the `<buildArg>` tag.
In this example, `-Ob` enables quick build mode.
Learn more in https://www.graalvm.org/latest/reference-manual/native-image/overview/BuildConfiguration/[Providing Configuration Options].

[[run-your-project]]
=== Build and run your project

Once you registered the plugin, you can use standard https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html[Maven phases].

Note that if you added the plugin inside the native profile, you should run your commands with `-Pnative` passed.
For example, you can build a native executable directly with Maven using:

[source,bash, role="multi-language-sample"]
----
mvn -Pnative package
----

This will generate native image under _target_ directory.

[TIP]
====
If Maven Surefire is using an older version of the JUnit Platform, you may experience some errors.
To solve this problem, we recommend using the following plugin:

[source,xml, role="multi-language-sample"]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>3.0.0</version>
</plugin>
----
====

[[advanced-use-cases]]
== Advanced Use Cases

For advanced users, the guide explains how to collect metadata, use diagnostics tools to analyze native executables, and includes examples of tests that demonstrate the guide's concepts.

[[configuration-options]]
=== Providing configuration options

You can provide configuring options to the native image inside `<configuration>` block specified inside the plugin block.

You can pass the following options:

* `<mainClass>` - If the execution fails with the no main manifest attribute, in target/<name>.jar error, the main class should be specified.
* `<imageName>` - The name of the native image. If a custom image name is not supplied, the artifact ID of the project will be used by default (defaults to the project name).
* `<debug>` - Determines if debug info should be generated (__false__ by default)
* `<verbose>` - Add verbose output (__false__ by default)
* `<quickBuild>` - Determines if image is being built in quick build mode
* <<maven-plugin.adoc#native-image-options,and many more...>>
You can also pass **build-time** options to the Native Image inside the following blocks:

Here is an example of additional options usage:

[source,xml, role="multi-language-sample"]
----
<configuration>
    <mainClass>org.graalvm.demo.Application</mainClass>
    <imageName>demoApp</imageName>
    <quickBuild>true</quickBuild>
    <debug>true</debug>
    <verbose>true</verbose>

    <buildArgs>
        <buildArg>--emit build-report</buildArg>
    </buildArgs>
</configuration>
----

[[collect-metadata]]
=== Collecting metadata with Tracing Agent

When your application uses dynamic language features such as **reflection**, **resources**, **serialization**, **proxies** or **jni**, additional metadata may be required.
The easiest way to collect missing metadata is with the Native Image Tracing Agent (link).

To enable the agent you should add the following block:

[source,xml, role="multi-language-sample"]
----
<agent>
    <enabled>true</enabled>
</agent>
----

From that point on, commands you execute will have the Native Image agent attached.

You can learn how to fine tune the agent <<maven-plugin.adoc#agent-support-configuring-options,here>>.

[TIP]
====
To enable the agent via the command line, supply the `-Dagent=true` flag when running Maven.
For example, you can run the agent defined in your __native profile__ like this:

[source,bash, role="multi-language-sample"]
----
mvn -Pnative -Dagent=true test
----
====

[[metadata-copy]]
=== Copy generated metadata to your source directory

By default, generated metadata will be placed inside _target/native/agent-output_ directory.
In many cases you may want to copy generated metadata to your _resources/META-INF_ directory.
To do so, you can configure and run `metadataCopy` task.

==== Configure metadataCopy task

First, you can configure `metadataCopy` task by adding a new block, named `metadataCopy` inside `agent` block that you added in the previous step.

Your `agent` block should look like this:

[source,xml, role="multi-language-sample"]
----
<agent>
    <enabled>true</enabled>
    <metadataCopy>
        <disabledStages>
            <stage>main</stage>
        </disabledStages>
        <merge>true</merge>
        <outputDirectory>/tmp/test-output-dir</outputDirectory>
    </metadataCopy>
</agent>
----

Inside this block, you can specify:

- `<outputDirectory>` - location where you want to copy the generated metadata
- `<disableStages>` - in case you don't want the agent output from the `main` or `test` phases, you can disable metadata copy for the concrete phase.
- `<merge>` - specifies whether the metadata you want to copy, should be merged with the metadata that already exists on the give location, or not. This only makes sense when there is already some existing metadata, created before.

[[execute-metadata-copy-task]]
==== Execute metadataCopy task

Once the `metadataCopy` task is configured, you can run the agent to collect the metadata (in this case for your tests) and copy it on the other location with:

[source,bash,subs="verbatim,attributes", role="multi-language-sample"]
----
mvn -Pnative test native:metadata-copy
----

[[maintain-generated-metadata]]
=== Maintain generated metadata

As your project develops, metadata files may need to be updated.
The best way to detect missing metadata is to run your native tests in your CI/CD pipeline.
When the native tests fail, due to missing metadata, you should:

1. Set `merge` option to true in the `metadataCopy` block
2. Run your tests again to generate new metadata (as we <<execute-metadata-copy-task, previously described>>)
3. Verify the correctness of the produced metadata and commit it to your repository

This way you will keep your original metadata, and add a new one.

[[reachability-metadata-repository]]
=== Reachability metadata repository

While we have described how you can add metadata for your own code, Native Build Tools (both Gradle and Maven plugins) makes use of metadata from Reachability Metadata Repository to ensure your application works out-of-box with 3rd party libraries that you depend on.
You can configure Reachability metadata support through `metadataRepository` block added to our main plugins' `configuration` block inside `pom.xml`.
Most common options you may want to configure in this block are:

* `<enabled>` - determines if you want to use Reachability metadata support or not (`true` by default)
* `<version>` - specifies exact Reachability metadata version you want to use

You can read more about __Reachability metadata support__ and other (advanced) configuring options, https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#_configuring_the_metadata_repository[here].

[[track-diagnostics]]
=== Using diagnostics

If you want to explore details about native images you are generating, check our https://www.graalvm.org/latest/reference-manual/native-image/overview/build-report/[build reports].
You can pass those options as standard build arguments in your `<configuration>` block.
