= Building Native Images with Maven: An End-to-End Guide
The GraalVM team
:highlighjsdir: {maven-relative-srcdir}/highlight

This guide walks you through integrating the Maven plugin for Native Image into your project.
It starts from enabling the plugin, building the first native image, and running it.

Then it takes you to more advanced use-cases such as plugin's configuration, applying optimizations, running native tests, and troubleshooting.
If you are an advanced user, you can skip the getting started part and go directly to the advanced section.

[[getting-started]]
== Getting Started
To compile your application ahead of time with https://www.graalvm.org/reference-manual/native-image/[GraalVM Native Image] and Maven, enable the Maven plugin for Native Image building. 
The plugin requires that you https://www.graalvm.org/downloads/[install GraalVM].

[[add-plugin]]
=== Add the Plugin

Add the plugin declaration to your _pom.xml_:

[source,xml, role="multi-language-sample"]
----
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>{maven-plugin-version}</version>
    <extensions>true</extensions>
    <executions>
      <execution>
        <id>build-native</id>
        <goals>
          <goal>compile-no-fork</goal>
        </goals>
        <phase>package</phase>
      </execution>
    </executions>
    <configuration>
        <mainClass>org.example.Main</mainClass>
    </configuration>
</plugin>
----

For convenience, you can create a Maven profile and add the plugin into it:

[source,xml, role="multi-language-sample"]
----
<profiles>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>{maven-plugin-version}</version>
            <extensions>true</extensions>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>compile-no-fork</goal>
                </goals>
                <phase>package</phase>
              </execution>
            </executions>
            <configuration>
              <mainClass>org.example.Main</mainClass>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
</profiles>
----

Replace `{maven-plugin-version}` with the latest available plugin version.
All plugin versions are listed https://github.com/graalvm/native-build-tools/releases[here].

The `<mainClass>` tag provides the path to the application main class (the main entry point).
Adjust the path according to your application sources.

[[run-your-project]]
=== Build and Run Your Application

Once you registered the plugin, you can use standard https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html[Maven phases].
If you added the plugin inside the `native` profile, run your commands with the `-Pnative` option.

- Build a native executable of your application.
This command will compile your application and create a native executable in the _target/_ directory.

[source,bash, role="multi-language-sample"]
----
mvn -Pnative package
----

- Run the application from the native executable:

[source,bash, role="multi-language-sample"]
----
./target/myApp
----

You can have multiple profiles, which is very convenient if you want to produce different versions of your native images for your application (optimized, static, and others).
Continue to advanced use cases to learn more.

[[advanced-use-cases]]
== Advanced Use Cases: How to

For advanced use cases, this guide provides instructions for configuring the build process, running tests on native code, gathering execution profiles, troubleshooting missing configurations, and enabling diagnostic tools to analyze native images.

[[configure-image-build]]
=== Configure Native Image Build

The plugin supports passing options directly to Native Image inside the `<configuration>` block.
Using `<buildArg>`, you can pass any Native Image build option listed on https://www.graalvm.org/reference-manual/native-image/overview/Options/[this website page].

The plugin also provides special tags to configure the build:

- `<environment>` - Sets the environment options
- `<imageName>` - Specifies of the name for the native executable file. If a custom name is not supplied, the artifact ID of the project will be used by default (defaults to the project name).
- `<jvmArgs>` - Passes the given argument directly to the JVM running the `native-image` tool
- `<quickBuild>` - Enables quick build mode
- `<verbose>` - Enables the verbose output
- and many more listed https://graalvm.github.io/native-build-tools/latest/maven-plugin.html#configuration-options[here].

Here is an example of additional options usage:
[source,xml, role="multi-language-sample"]
----
<configuration>
  <mainClass>org.example.Main</mainClass>
  <imageName>myApp</imageName>
  <verbose>true</verbose>
  <buildArgs>
      <buildArg>-O3</buildArg> <!-- enables additional compiler optimizations -->
  </buildArgs>
  <environment>
      <variable1>value1</variable1>
      <variable2>value2</variable2>
  </environment>
  <jvmArgs>
      <arg>your-argument</arg>
  </jvmArgs>
</configuration>
----

[TIP]
====
As an alternative, you can pass additional build options via the `NATIVE_IMAGE_OPTIONS` environment variable, on the command line.
This works similarly to `JAVA_TOOL_OPTIONS``, where the value of the environment variable is prefixed to the options supplied to `native-image`.
====

Learn more about Native Image build configuration https://www.graalvm.org/reference-manual/native-image/overview/BuildConfiguration/[on the website].

[[run-junit-tests]]
=== Run Junit Tests

This plugin supports running tests on the JUnit Platform.
The tests are compiled ahead of time and executed as native code.

- To execute tests, add one more `<execution>` to the plugin declaration:

[source,xml, role="multi-language-sample"]
----
<execution>
  <id>test-native</id>
  <goals>
    <goal>test</goal>
  </goals>
  <phase>test</phase>
</execution>
----

- Add the JUnit 5 dependency to _pom.xml_ to include the testing framework. It will only be used during the `test` phase and not included in the final build artifact:

[source,xml, role="multi-language-sample"]
----
<dependency>
    <groupId>org.junit.jupiter</groupId>
    <artifactId>junit-jupiter</artifactId>
    <version>5.10.0</version>
    <scope>test</scope>
</dependency>
----

- Run the tests:

[source,bash, role="multi-language-sample"]
----
mvn -Pnative test
----

The new execution you have just added, `test-native`, integrates with the Maven `test` phase.
First, Maven runs the tests on the JVM, then compiles them ahead of time and executes them as native code.

==== Disable tests

If you wish to disable tests on the JVM as well as running native code tests, invoke Maven with the `-DskipTests` flag. 
This flag is supported by the Maven Surefire plugin and Native Build Tools. 

[source,bash, role="multi-language-sample"]
----
mvn -Pnative -DskipTests package
----

If you wish to run tests on the JVM with Maven Surefire, but skip running tests as native code, invoke Maven with the `-DskipNativeTests` flag.
This flag is specific to Native Build Tools.

[source,bash, role="multi-language-sample"]
----
mvn -Pnative -DskipNativeTests package
----

Alternatively, set `<skipNativeTests>` to `true` in the plugin configuration: 

[source,xml, role="multi-language-sample"]
----
<configuration>
  <mainClass>org.example.Main</mainClass>
  <skipNativeTests>true</skipNativeTests>
</configuration>
----

This way you configure your Maven profile to skip generation and execution of tests as native code.

[[gather-execution-profiles]]
=== Gather Execution Profiles and Build Optimized Images

You may want to gather profiling information from your application's execution to pinpoint areas of inefficiency.
With this profiling data, you can also build an optimized native image.

The technique for building native images optimized on profiles is called https://www.graalvm.org/latest/reference-manual/native-image/optimizations-and-performance/PGO/[Profile-Guided Optimization (PGO)].
With PGO you can “train” your native application for specific workloads to improve performance and throughput.
The PGO workflow includes three steps.

[TIP]
====
PGO is available in Oracle GraalVM.
====

Step 1: **Build an instrumented native image** by passing the `--pgo-instrument` option to `native-image` using `<buildArg>`.
To prevent overwriting a previously built native executable, we recommend either creating a separate Maven profile for each build or specifying a unique file name using the `<imageName>` tag.
For example:

[source,xml, role="multi-language-sample"]
----
<configuration>
  <mainClass>org.example.Main</mainClass>
  <imageName>instrumentedApp</imageName>
  <buildArgs>
      <buildArg>--pgo-instrument</buildArg>
  </buildArgs>
</configuration>
----

Step 2: **Gather profiles** by running the instrumented executable.
By default, the _default.iprof_ file, if not specified otherwise, is generated alongside the native executable.

[source,bash, role="multi-language-sample"]
----
./target/instrumentedApp
----

Step 3. **Build an optimized native image with profiles** by passing the `--pgo` option.
You may want to provide a different name for the native image or create another Maven profile to handle this configuration:

[source,xml, role="multi-language-sample"]
----
<configuration>
  <mainClass>org.example.Main</mainClass>
  <imageName>optimizedApp</imageName>
  <buildArgs>
      <buildArg>--pgo</buildArg>
  </buildArgs>
</configuration>
----

If the profile file has the default name and location, it will be automatically picked up. Alternatively, you can specify the file path as following: `--pgo=myprofile.iprof`.

Once the optimized image is built, run it.
The application's performance when running from this native executable should be comparable to, or even faster than, running on the JVM.
Learn more about PGO https://www.graalvm.org/reference-manual/native-image/optimizations-and-performance/PGO/basic-usage[on the website].

[[troubleshoot-missing-configuration]]
=== Troubleshoot Missing Configuration
 
[[detect-missing-metadata]]
==== Detect Missing Metadata

Quite possibly, your application relies on external libraries.
If your application uses a well-supported framework such as Spring or Micronaut, its dependencies should be compatible with Native Image.
Frameworks and libraries that support Native Image by default provide configurations in the https://github.com/oracle/graalvm-reachability-metadata[GraalVM Reachability Metadata Repository]. 
When you build a native image, Native Build Tools reference this repository to apply the required configuration automatically.

[TIP]
====
You can find an extensive list of libraries and frameworks from the Java ecosystem tested with Native Image on https://www.graalvm.org/native-image/libraries-and-frameworks/[this page].
====

However, it may happen, that your native image crashes at run time with a missing class error.
To address this, start by checking if any required configuration is missing.

The best way to detect missing metadata is by running your native tests in a CI/CD pipeline.
Alternatively, you can **identify missing configuration manually** using the following method.

- Pass the `--exact-reachablity-metadata` option to the `native-image` tool in _pom.xml_, as shown below:

[source,xml, role="multi-language-sample"]
----
<configuration>
  <mainClass>org.example.Main</mainClass>
  <buildArgs>
      <buildArg>--exact-reachablity-metadata</buildArg>
  </buildArgs>
</configuration>
----

- Rebuild the application with Maven:

[source,bash, role="multi-language-sample"]
----
mvn -Pnative package
----

- Run the application from the native executable with the `-XX:MissingRegistrationReportingMode=Warn` option: 

[source,bash, role="multi-language-sample"]
----
./target/yourApp -XX:MissingRegistrationReportingMode=Warn
----

- If there is any missing metadata printed to the console, **add it to the configuration file manually**, as described https://www.graalvm.org/reference-manual/native-image/metadata/#specifying-metadata-with-json[here], or **collect it automatically using the Tracing agent**.
(See next.) 

- Rebuild your native image and test again.

[[collect-metadata]]
==== Collect Metadata Automatically with Tracing Agent

Your application may use dynamic Java features such as reflection, serialization, or resource loading.
It is also possible that a framework your application relies on uses a library dependency incompatible with Native Image.
In such cases, additional metadata is required.

The easiest way to collect the missing metadata is by using the https://www.graalvm.org/reference-manual/native-image/metadata/AutomaticMetadataCollection/[Tracing Agent].
This agent tracks all usages of dynamic features during application execution on the JVM and generates the necessary configuration.

The agent is disabled by default.
You can enable it on the command line or in _pom.xml_.

To enable the agent via the command line, pass the `-Dagent=true` option when running Maven:

[source,bash, role="multi-language-sample"]
----
mvn -Pnative -Dagent=true package
----

[TIP]
====
Enabling the agent via the command line only attaches it for a specific run; it does not automatically run every time you build the application.
====

To enable the agent in _pom.xml_ and collect missing metadata, do the following.

Step 1: **Enable the agent** by setting `<agent>` to `true` in the `native` profile:

[source,xml, role="multi-language-sample"]
----
<configuration>
    <mainClass>org.example.Main</mainClass>
    <agent>
        <enabled>true</enabled>
    </agent>
</configuration>
----
From that point on, commands you execute run with the agent attached.
By default, the agent creates the metadata in the _target/native/agent-output_ directory.

Step 2: **Copy the generated metadata** from the default location, _target/native/agent-output/_, to the resources directory, for example, _resources/META-INF/_.
To do that with Maven, configure and run the `metadataCopy` task.

Add a new task named `metadataCopy` inside the `agent` block that you added in step 1. 
Your configuration should look like this:

[source,xml, role="multi-language-sample"]
----
<agent>
    <enabled>true</enabled>
    <metadataCopy>
        <disabledStages>
            <stage>main</stage>
        </disabledStages>
        <merge>true</merge>
        <outputDirectory>resources/META-INF/</outputDirectory>
    </metadataCopy>
</agent>
----

In this block:
 
- `<outputDirectory>` specifies location where you want to copy the generated metadata.
- `<disableStages>` - you can disable metadata copy for a concrete Maven phase. In this you do not want the agent output from the `main` phase.
- `<merge>` - specifies whether the metadata you want to copy, should be merged with the metadata that already exists in the given location, or not. This only makes sense when there is already some existing metadata, created before.

Step 3: Now that the `metadataCopy` task is configured, **run the agent to collect the metadata and copy it to the other location** with:

[source,bash,subs="verbatim,attributes", role="multi-language-sample"]
----
mvn -Pnative test native:metadata-copy
----

Step 4: Finally, **build the native image with the metadata** and run:
[source,bash, role="multi-language-sample"]
----
mvn -Pnative package
----

If your native image is successfully build, but fails at run time, check the troubleshooting guide https://www.graalvm.org/reference-manual/native-image/guides/troubleshoot-run-time-errors/[Troubleshoot Native Image Run-Time Errors].

Learn more about how to fine-tune the agent further <<maven-plugin.adoc#agent-support-configuring-options,here>>.

[[use-diagnostics-tools]]
=== Use Diagnostics Tools

If you need to diagnose the native applications you generate, or monitor your Java application when launched from a native executable, Native Image offers tools for debugging and analyzing the produced binary.
For example:

[source,xml, role="multi-language-sample"]
----
<configuration>
    <mainClass>org.example.Main</mainClass>
    <debug>true</debug>
    <buildArgs>
        <buildArg>--emit build-report</buildArg>
        <buildArg>--enable-monitoring=jfr</buildArg>
    </buildArgs>
</configuration>
----

- The `--emit build-report` option generates an HTML page report alongside the native executable that you can open in a browser.
It provides broad information about each build stage as well as the generated binary’s contents. You can read more about Build Report features https://www.graalvm.org/latest/reference-manual/native-image/overview/build-report/[here].

[TIP]
====
Build Report is available in Oracle GraalVM.
When running on GraalVM for JDK 21, pass the `-H:+BuildReport` option instead to generate a build report.
====

- The `--enable-monitoring=jfr` instructs the plugin to https://www.graalvm.org/reference-manual/native-image/guides/build-and-run-native-executable-with-jfr/[build a native executable with the JDK Flight Recorder (JFR) support]. 

- The `<debug>` option generates a native executable with debug information for https://www.graalvm.org/reference-manual/native-image/guides/debug-native-image-process/[source-level debugging with the GNU Debugger (GDB)].

All the monitoring and debugging tools https://www.graalvm.org/reference-manual/native-image/debugging-and-diagnostics/[listed on the website], can be enabled in the plugin configuration using `<buildArgs>`.

=== Learn more

To continue learning, refer to the <<changelog.adoc#,extensive reference documentation for the GraalVM Native Image Maven plugin>>.
