= Setting up GraalVM with native-image support

image:https://www.graalvm.org/resources/img/logo-colored.svg[GraalVM]

Working GraalVM distribution with `native-image` installable and `GRAALVM_HOME` and/or `JAVA_HOME` environment variables set, is prequisite for successful *native-image* building.

Following are the steps needed to obtain and setup GraalVM environment.

NOTE: This is just a quick overview, and that user should consult https://www.graalvm.org/docs/getting-started/[Getting Started section] in official documentation before proceeding.

== 1. Obtaining distribution

GraalVM distributions can be obtained from https://www.graalvm.org/downloads/[official website].
Development builds might be available at `releases` section of https://github.com/graalvm/?q=graalvm-ce[official GraalVM Github page projects].

== 2. Setting up environment variables

After obtaining GraalVM distribution environment variable `GRAALVM_HOME` should be set to point to it.

This can be achieved using:

.Linux
```bash
export GRAALVM_HOME=/home/${current_user}/path/to/graalvm
```

.macOS
```bash
export GRAALVM_HOME=/Users/${current_user}/path/to/graalvm/Contents/Home
```

.Windows
```batch
setx /M GRAALVM_HOME "C:\path\to\graalvm"
```

NOTE: Preferably user would also set `JAVA_HOME` variable in the same manner (by replacing `GRAALVM_HOME` with `JAVA_HOME` in previous commands).

== 3. `native-image` tool instalation

.Linux / macOS
```bash
$GRAALVM_HOME/bin/gu install native-image
```

.Windows
```batch
%GRAALVM_HOME%/bin/gu install native-image
```
