= Setting up GraalVM with Native Image Support

image:https://www.graalvm.org/resources/img/logo-colored.svg[GraalVM]

A prerequisite for using the Gradle or Maven plugin for GraalVM Native Image is to install GraalVM.
Follow the steps below to setup a GraalVM environment.

[NOTE]
====
This is just a quick overview, and users can consult the https://www.graalvm.org/docs/getting-started/[GraalVM Getting Started] before proceeding.
====

== 1. Download GraalVM

The easiest way to download GraalVM is to use the https://sdkman.io/jdks[SDKMAN!].
To install GraalVM for JDK 20 or JDK 17, run:
```
sdk install java 20.0.1-graal
sdk install java 17.0.7-graal
```
GraalVM installation includes Native Image.

== 2. Set up Environment Variables

After obtaining a GraalVM distribution, set the `JAVA_HOME` and `PATH` environment variable.

This can be achieved using this command:

.Linux
```bash
export JAVA_HOME=/home/${current_user}/path/to/graalvm
```

.macOS
```bash
export JAVA_HOME=/Users/${current_user}/path/to/graalvm/Contents/Home
```

.Windows
```batch
setx /M JAVA_HOME "C:\path\to\graalvm"
```

In the same manner, set up the `PATH` environment variable:

.Linux
```bash
export JAVA_HOME=/home/${current_user}/path/to/graalvm/bin:$PATH
```

.macOS
```bash
export JAVA_HOME=/Users/${current_user}/path/to/graalvm/Contents/Home/bin:$PATH

```

.Windows
```batch
setx /M JAVA_HOME "C:\path\to\graalvm\bin;%PATH%"
```

For other installation options, go to the https://www.graalvm.org/downloads/[official website].

Development builds might be available at `releases` section of https://github.com/graalvm/?q=graalvm-ce[official GraalVM Github page projects].