= Getting Started with Gradle Plugin for GraalVM Native Image
The GraalVM team
:highlighjsdir: {gradle-relative-srcdir}/highlight

This guide shows how to get started with the <<gradle-plugin.adoc#,Gradle plugin for GraalVM Native Image>> and build a native executable for a Java application.

You will create a sample application, enable the plugin, add support for dynamic features, build a native executable, and run JUnit tests.

Two ways of building a native executable using the plugin will be demonstrated:

- <<#build-a-native-executable-with-resources-autodetection,Build a Native Executable with Resources Autodetection>>
- <<#build-a-native-executable-detecting-resources-with-the-agent,Build a Native Executable Detecting Resources with the Agent>>

====
The plugin requires that you https://www.graalvm.org/latest/docs/getting-started/[setup GraalVM].

The easiest way to install GraalVM is to use https://sdkman.io/jdks[SDKMAN!].

For other installation options, go to https://www.graalvm.org/downloads/[GraalVM Downloads].
====

== Prepare a Demo Application

====
You start by creating a **Fortune Teller** sample application that simulates the traditional
https://en.wikipedia.org/wiki/Fortune_(Unix)[fortune Unix program].
The data for the fortune phrases is provided by https://github.com/your-fortune[YourFortune].
====

. Create a new Java project with *Gradle* using the following command (alternatively, you can use your IDE to generate a project):
+
[source,shell]
----
gradle init --project-name fortune-parent --type java-application --package demo --test-framework junit-jupiter --dsl groovy
----
. Rename the default _app_ directory to _fortune_, edit the _settings.gradle_ file to replace `app` with `fortune`, then rename the default filename _App.java_ to _Fortune.java_, and replace its contents with the following:
+
[source,java]
----
package demo;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Fortune {

    private static final Random RANDOM = new Random();
    private final ArrayList<String> fortunes = new ArrayList<>();

    public Fortune() throws JsonProcessingException {
        // Scan the file into the array of fortunes
        String json = readInputStream(ClassLoader.getSystemResourceAsStream("fortunes.json"));
        ObjectMapper omap = new ObjectMapper();
        JsonNode root = omap.readTree(json);
        JsonNode data = root.get("data");
        Iterator<JsonNode> elements = data.elements();
        while (elements.hasNext()) {
            JsonNode quote = elements.next().get("quote");
            fortunes.add(quote.asText());
        }
    }

    private String readInputStream(InputStream is) {
        StringBuilder out = new StringBuilder();
        try (InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
             BufferedReader reader = new BufferedReader(streamReader)) {
            String line;
            while ((line = reader.readLine()) != null) {
                out.append(line);
            }

        } catch (IOException e) {
            Logger.getLogger(Fortune.class.getName()).log(Level.SEVERE, null, e);
        }
        return out.toString();
    }

    public String randomFortune() {
        // Pick a random number
        int r = RANDOM.nextInt(fortunes.size());
        // Use the random number to pick a random fortune
        return fortunes.get(r);
    }

    private void printRandomFortune() throws InterruptedException {
        String f = randomFortune();
        // Print out the fortune s.l.o.w.l.y
        for (char c : f.toCharArray()) {
            System.out.print(c);
            Thread.sleep(100);
        }
        System.out.println();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws InterruptedException, JsonProcessingException {
        Fortune fortune = new Fortune();
        fortune.printRandomFortune();
    }
}
----
. Delete the _fortune/src/test/java_ directory (you will add tests in a later stage).
. Copy and paste the following file,
https://raw.githubusercontent.com/graalvm/graalvm-demos/master/fortune-demo/fortune/src/main/resources/fortunes.json[fortunes.json] under _fortune/src/main/resources/_.
Your project tree should be:
+
[source,shell]
----
.
├── fortune
│   ├── build.gradle
│   └── src
│       ├── main
│       │   ├── java
│       │   │   └── demo
│       │   │       └── Fortune.java
│       │   └── resources
│       │       └── fortunes.json
│       └── test
│           └── resources
├── gradle
│   └── wrapper
│       ├── gradle-wrapper.jar
│       └── gradle-wrapper.properties
├── gradlew
├── gradlew.bat
└── settings.gradle
----
. Open the Gradle configuration file _build.gradle_, and update the main class in the `application` section:
+
[source,xml]
----
application {
    mainClass = 'demo.Fortune'
}
----
. Add explicit FasterXML Jackson dependencies that provide functionality to read and write JSON, data bindings (used in the demo application). 
Insert the following three lines in the `dependencies` section of _build.gradle_:
+
[source,xml]
----
implementation 'com.fasterxml.jackson.core:jackson-core:2.13.2'
implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.2.2'
implementation 'com.fasterxml.jackson.core:jackson-annotations:2.13.2'
----
+
Also, remove the dependency on `guava` that will not be used.
+
The next steps demonstrate what you should do to enable the
https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html[Gradle Plugin for GraalVM Native Image].
. Register the plugin. Add the following to `plugins` section of your project’s _build.gradle_ file:
+
[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  id 'org.graalvm.buildtools.native' version '{gradle-plugin-version}'
}
----
+
[source,kotlin,subs="verbatim,attributes",role="multi-language-sample"]
----
plugins {
  id("org.graalvm.buildtools.native") version "{gradle-plugin-version}"
}
----
+
The `{gradle-plugin-version}` block pulls the latest plugin version.
Replace it with a specific version if you prefer.
The plugin discovers which JAR files it needs to pass to the `native-image` builder and what the executable main class should be.

[[build-a-native-executable-with-resources-autodetection]]
== Build a Native Executable with Resources Autodetection

You can already build a native executable by running `./gradlew nativeCompile` or run it directly by invoking `./gradlew nativeRun`.
However, at this stage, running the native executable will fail because this application requires additional metadata: you need to provide it with a list of resources to load.

. Instruct the plugin to automatically detect resources to be included in the native executable.
Add this to your _build.gradle_ file:
+
[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        resources.autodetect()
    }
}
----
+
[source,kotlin,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    binaries.all {
        resources.autodetect()
    }
}
----
[start=2]
. Compile the project and build a native executable at one step:
+
[source,shell]
----
./gradlew nativeRun
----
+
The native executable, named _fortune_, is created in the _/fortune/build/native/nativeCompile_ directory.
[start=3]
. Run the native executable:
+
[source,shell]
----
./fortune/build/native/nativeCompile/fortune
----
+
The application starts and prints a random quote.

Configuring the `graalvmNative` plugin to automatically detect resources (`resources.autodetect()`) to be included in a binary is one way to make this example work.
Using `resources.autodetect()` works because the application uses resources (_fortunes.json_) which are directly available in the `src/main/resources` location.

In the next section, the guide shows that you can use the tracing agent to do the same.

[[build-a-native-executable-detecting-resources-with-the-agent]]
== Build a Native Executable by Detecting Resources with the Agent

The Native Image Gradle plugin simplifies generation of the required metadata by injecting the
https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#agent-support[
tracing agent] automatically for you at compile time.
To enable the agent, just pass the `-Pagent` option to any Gradle tasks that extends `JavaForkOptions` (for example, `test` or `run`).

The following steps illustrate how to collect metadata using the agent, and then build a native executable using that metadata.

. To demonstrate this approach, remove the `resources.autodetect()` block from your _build.gradle_ file:
+
[source,shell]
----
binaries.all {
    resources.autodetect()
}
----
. Run your application with the agent enabled:
+
[source,shell]
----
./gradlew -Pagent run
----
It runs your application on the JVM with the agent, collects the metadata, and generates configuration files in the _$\{buildDir}/native/agent-output/$\{taskName}_ directory.
. Copy the configuration files into the project's _/META-INF/native-image_ directory using the `metadataCopy` task:
+
[source,shell]
----
./gradlew metadataCopy --task run --dir src/main/resources/META-INF/native-image
----
. Build a native executable using metadata acquired by the agent:
+
[source,shell]
----
./gradlew nativeCompile
----
+
The native executable, named _fortune_, is created in the _build/native/nativeCompile_ directory.
. Run the native executable:
+
[source,shell]
----
./fortune/build/native/nativeCompile/fortune
----
+
The application starts and prints a random quote.

== Add JUnit Testing

The Gradle plugin for GraalVM Native Image can run
https://junit.org/junit5/docs/current/user-guide/[JUnit Platform] tests on your native executable.
This means that the tests will be compiled and run as native code.

. Create the following test in the
_fortune/src/test/java/demo/FortuneTest.java_ file:
+
.fortune/src/test/java/demo/FortuneTest.java
[source,java]
----
package demo;

import com.fasterxml.jackson.core.JsonProcessingException;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class FortuneTest {
    @Test
    @DisplayName("Returns a fortune")
    void testItWorks() throws JsonProcessingException {
        Fortune fortune = new Fortune();
        assertTrue(fortune.randomFortune().length()>0);
    }
}
----

. Run JUnit tests:
[source,shell]
----
./gradlew nativeTest
----

The plugin runs tests on the JVM prior to running tests from the native executable.
To disable testing support (which comes by default), add the following configuration to the _build.gradle_ file:

[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    testSupport = false
}
----

[source,kotlin,subs="verbatim,attributes", role="multi-language-sample"]
----
graalvmNative {
    testSupport.set(false)
}
----

=== Summary

The Gradle plugin for GraalVM Native Image adds support for building and testing native executables using the https://gradle.org[Gradle].
The plugin has many features, described in the 
https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html[plugin
reference documentation].