= Gradle plugin for GraalVM Native Image building
The GraalVM team
:highlighjsdir: {gradle-relative-srcdir}/highlight

image:https://github.com/graalvm/native-build-tools/actions/workflows/test-native-gradle-plugin.yml/badge.svg[]

== Introduction

The {doctitle} adds support for building and testing native images using the https://gradle.org[Gradle build tool].

For upgrading please take a look at the <<index.adoc#changelog,Changelog>>.

== Quickstart

=== Adding the plugin

Add following to `plugins` section of your project's `build.gradle` / `build.gradle.kts`:

.Applying the plugin
[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  // ...

  // Apply GraalVM Native Image plugin
  id 'org.graalvm.buildtools.native' version '{gradle-plugin-version}'
}
----

[source,kotlin,subs="verbatim,attributes",role="multi-language-sample"]
----
plugins {
  // ...

  // Apply GraalVM Native Image plugin
  id("org.graalvm.buildtools.native") version "{gradle-plugin-version}"
}
----

The plugin isn't available on the https://plugins.gradle.org[Gradle Plugin Portal] yet, so you will need to declare a plugin repository in addition:

Add the following to your `settings.gradle` / `settings.gradle.kts`:

.Declaring the plugin repository
[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/settings.gradle[tags=plugin-management]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/settings.gradle.kts[tags=plugin-management]
----

[TIP]
.Testing pre-releases
====
You can use development versions of the plugin by adding our snapshot repository instead. Pre-releases are provided for convenience, without any guarantee.
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/settings.gradle[tags=pre-release, indent=0]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/settings.gradle.kts[tags=pre-release, indent=0]
----
====

=== Installing GraalVM Native Image tool

The plugin relies on Gradle's https://docs.gradle.org/7.1.1/userguide/toolchains.html[JVM toolchain support], allowing to decorrelate the tool used to run Gradle, the compiler used to build your application, and eventually the SDK used to generate a native image.

In practice, it means that this plugin will try to locate a suitable installation of GraalVM for you, even if you don't run Gradle itself with GraalVM.
For this, it will look into conventional places on your machine, including from installations done by popular tools like https://sdkman.io/[SDKMAN!] or https://github.com/shyiko/jabba[Jabba].

WARNING: Even if you have a GraalVM SDK installed, Gradle will _not_ automatically detect if `native-image` is also installed.
Therefore, you will need to make sure that you have executed `gu install native-image` as indicated in the <<graalvm-setup.adoc#,setup instructions>>.

If Gradle cannot find a GraalVM installation on the machine, it will fail with an error like this:

----
> No compatible toolchains found for request filter: {languageVersion=11, vendor=matching('GraalVM'), implementation=vendor-specific} (auto-detect true, auto-download true)
----

This happens because there's no automatic provisioning of the GraalVM toolchain available yet, so you will have to install it first.
Follow the <<graalvm-setup.adoc#,following instructions>> to install it properly.

Alternatively, you may choose to:

1. <<configuration-toolchains-disabling, Disable toolchain support>>
2. Run Gradle itself with a GraalVM SDK
3. Set up a `GRAALVM_HOME` environment variable pointing to your GraalVM installation

Note that none of the above options is recommended as they are more fragile.

[[configuration]]
== Configuration

This plugin works with the `application` plugin and will register a number of tasks and extensions for you to configure.

=== Available tasks

The main tasks that you will want to execute are:

- `nativeCompile`, which will trigger the generation of a native executable of your application
- `nativeRun`, which executes the generated native executable
- `nativeTestCompile`, which will build a native image with tests found in the `test` source set
- `nativeTest`, which will <<testing-support,execute tests>> found in the `test` source set in native mode

Those tasks are configured with reasonable defaults using the `graalvmNative` extension `binaries` container of type link:javadocs/native-gradle-plugin/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.html[NativeImageOptions].

The main executable is configured by the image named `main`, while the test executable is configured via the image named `test`.

=== Native image options

The link:javadocs/native-gradle-plugin/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.html[NativeImageOptions] allows you to tweak how the native image is going to be built.

[[configuration-toolchains]]
==== Selecting the GraalVM toolchain

By default, the plugin will select a Java 11 GraalVM toolchain.
If you want to use a different toolchain, for example a GraalVM Community Edition for Java 8, you can configure the toolchain like this:

.Selecting the GraalVM toolchain
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=select-toolchain]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=select-toolchain]
----

[[configuration-toolchains-disabling]]
===== Disabling toolchain detection

Because of limitations in Gradle, the plugin may not be able to properly detect the toolchain.
This is the case if, for example, you want to use GraalVM Enterprise or you want to be able to select a particular version of GraalVM.

To work around this problem, you can disable toolchain detection:

.Disabling toolchain detection
[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=disabling-toolchain, indent=0]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=disabling-toolchain, indent=0]
----

If you do this, the plugin will search for 2 environment variables: `GRAALVM_HOME` and `JAVA_HOME` _in that order_.
If one of them is set, it will assume that it points to a valid GraalVM installation and completely bypass toolchain selection.
Therefore, it becomes your responsibility to make sure that the environment variable points to a JDK that is compatible with your build script requirements (in particular, the language version).

[[configuration-options]]
==== Configuration options

The following configuration options are available for building images:

.NativeImageOption configuration
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=all-config-options]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=all-config-options]
----

NOTE: For options that can be set using command-line, if both DSL and command-line options are present, command-line options take precedence.

[[long_classpath_and_fat_jar_support]]
==== Long classpath, @argument file and fat jar support

Since release 0.9.10, the plugin will automatically pass arguments to the `native-image` tool using an argument file, which should prevent all https://github.com/graalvm/native-build-tools/issues/85[long classpath issues] under Windows.
However, if you are using an older GraalVM release (older than 21.3) which doesn't support argument files, you will need to rely on creating a "fat jar", which includes all entries from the classpath automatically, to workaround the problem:

.Enabling the fat jar creation
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=enable-fatjar]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=enable-fatjar]
----

Alternatively, it is possible to use your own fat jar (for example created using the https://imperceptiblethoughts.com/shadow/[Shadow plugin]) by setting the `classpathJar` property directly on the _task_:

.Enabling a custom fat jar creation
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=custom-fatjar]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=custom-fatjar]
----

When the `classpathJar` property is set, the `classpath` property is _ignored_.

[[testing-support]]
== Testing support

This plugin supports running tests on the
https://junit.org/junit5/docs/current/user-guide/[JUnit Platform] as native images. This
means that tests will be compiled and executed as native code.

In theory, any `TestEngine` supported on the JUnit Platform should be supported by this
plugin as long as the programming language used by the `TestEngine` and the programming
language used to write the tests is supported in a GraalVM native image. This plugin
provides explicit support for the JUnit Jupiter and JUnit Vintage test engines, and
support for additional test engines should be possible with custom native configuration.

Currently, this feature requires the execution of the tests in the classic "JVM" mode _prior to_ the execution of tests in native mode. To execute the tests, execute:

[source,bash]
----
./gradlew nativeTest
----

NOTE: This plugin requires JUnit Platform 1.8 or higher.

[[mockito-bytebuddy-support]]
=== Mockito / Byte Buddy support

Mockito is supported starting from version 4.5.0 (ByteBuddy >= 1.12.9) with GraalVM >= 22.1.
However, you need to add the following configuration to make it work with GraalVM 22.1:

.Enabling Mockito / Byte Buddy support on GraalVM 22.1
[source,groovy,role="multi-language-sample"]
----
graalvmNative {
    binaries {
        test {
            buildArgs.add("--rerun-class-initialization-at-runtime=net.bytebuddy.ClassFileVersion,net.bytebuddy.utility.dispatcher.JavaDispatcher,net.bytebuddy.utility.Invoker$Dispatcher")
            buildArgs.add("--initialize-at-build-time=net.bytebuddy.description.method.MethodDescription$InDefinedShape$AbstractBase$ForLoadedExecutable,net.bytebuddy.description.type.TypeDescription$AbstractBase,net.bytebuddy.description.type.TypeDescription$ForLoadedType,net.bytebuddy.description.method.MethodDescription$ForLoadedMethod,net.bytebuddy.implementation.bind.annotation.Argument$BindingMechanic,net.bytebuddy.implementation.bind.annotation.Argument$BindingMechanic$1,net.bytebuddy.implementation.bind.annotation.Argument$BindingMechanic$2,net.bytebuddy.implementation.bind.annotation.Super$Instantiation$2")
        }
    }
}
----

[source,kotlin,role="multi-language-sample"]
----
graalvmNative {
    binaries {
        named("test") {
            buildArgs.add("--rerun-class-initialization-at-runtime=net.bytebuddy.ClassFileVersion,net.bytebuddy.utility.dispatcher.JavaDispatcher,net.bytebuddy.utility.Invoker$Dispatcher")
            buildArgs.add("--initialize-at-build-time=net.bytebuddy.description.method.MethodDescription$InDefinedShape$AbstractBase$ForLoadedExecutable,net.bytebuddy.description.type.TypeDescription$AbstractBase,net.bytebuddy.description.type.TypeDescription$ForLoadedType,net.bytebuddy.description.method.MethodDescription$ForLoadedMethod,net.bytebuddy.implementation.bind.annotation.Argument$BindingMechanic,net.bytebuddy.implementation.bind.annotation.Argument$BindingMechanic$1,net.bytebuddy.implementation.bind.annotation.Argument$BindingMechanic$2,net.bytebuddy.implementation.bind.annotation.Super$Instantiation$2")
        }
    }
}
----

[[testing-support-disabling]]
=== Disabling testing support

There are cases where you might want to disable native testing support:

- You don't actually want to run your tests in native mode.
- Your library or application uses a testing framework that is not supported on the JUnit
  Platform.
- You need to use the <<agent-support, agent>> when running tests on the JVM but do not
  wish to run those same tests in native mode.

In this case, you can disable native testing support by configuring the `graalvmNative`
extension as follows:

.Disabling testing support
[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=disable-test-support]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=disable-test-support]
----

[[extra-test-suites]]
=== Configuring additional test suites

It's common to have multiple test source sets in a Gradle build.
Typically, you may have an integration test suite, or a functional test suite, in addition to the unit test suite.
The plugin supports running those tests as native binaries too.

For example, imagine that you have a source set named `integTest` and that its corresponding test task is named `integTest`.
In this case you can register a new native test binary via the `graalvmNative` extension:

.Registering a new test suite
[source, groovy, role="multi-language-sample"]
----
include::../../../../samples/java-application-with-custom-tests/build.gradle[tag=register-native-test]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=custom-binary]
----

The plugin will then automatically create the following tasks:

- `nativeIntegTestCompile`, to compile a native image using the `integTest` source set
- `nativeIntegTest`, to execute the tests in native mode

The same mechanism can be used if you have multiple test tasks for a single test source set, which is often the case with manual test sharding.

[[agent-support]]
== Reflection support and running with the native agent

If your project requires reflection, classpath resources, dynamic proxies or other features requiring explicit native configuration, it may prove helpful to first run your application or tests using the https://www.graalvm.org/reference-manual/native-image/Agent/[`native-image-agent`].

The Native Image Gradle plugin simplifies generation of the required metadata files by injecting the agent automatically for you (this includes, but is not limited to the reflection file).

Any task that extends `JavaForkOptions` (like `test`, `run` etc) can be instrumented by passing `-Pagent` to gradle when running said tasks.

The agent can run in multiple modes that dictate how the metadata is collected and merged.

Once the metadata is collected, it can be copied into the project using the `metadataCopy` task.

[source,bash]
----
./gradlew -Pagent run # Runs on JVM with native-image-agent.
./gradlew metadataCopy --task run --dir src/main/resources/META-INF/native-image # Copies the metadata collected by the agent into the project sources
./gradlew nativeCompile # Builds image using metadata acquired by the agent.

# For testing
./gradlew -Pagent nativeTest # Runs on JVM with the native-image agent, collects the metadata and uses it for testing on native-image.
----

The agent can run in multiple modes:

* Standard - Collects metadata without conditions. This is recommended if you are building an executable.
* Conditional - Collects metadata with conditions. This is recommended if you are creating conditional metadata for a library intended for further use.
* Direct - For advanced users only. This mode allows directly controlling the command line passed to the agent.

The default mode is specified in the DSL but can be changed by passing the mode name to Gradle when using the agent: `-Pagent=conditional`

The generated configuration files will be found in the `${buildDir}/native/agent-output/${taskName}` directory, for example, `build/native/agent-output/run`.
The plugin will also substitute `{output_dir}` in the agent options to point to this directory during the agent run.

[[agent-support-configuring-options]]
=== Configuring agent options

The native agent can be configured https://www.graalvm.org/reference-manual/native-image/Agent/[with additional options].
This can be done using the `agent` configuration block.
Each agent option has a corresponding field in the DSL.
See <<configuration-options>> for the full list of available options.


[[metadata-support]]
== GraalVM Reachability Metadata Support

Since release 0.9.11, the plugin adds experimental support for the https://github.com/graalvm/graalvm-reachability-metadata/[GraalVM reachability metadata repository].
This repository provides GraalVM configuration for libraries which do not officially support GraalVM native.

=== Enabling the metadata repository

Support needs to be enabled explicitly:

.Enabling the metadata repository
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=enable-metadata-repository]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=enable-metadata-repository]
----

A metadata repository consists of configuration files for GraalVM.
The plugin will automatically download the configuration metadata from the official repository if you supply the version of the repository you want to use:

.Enabling the metadata repository
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=specify-metadata-repository-version]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=specify-metadata-repository-version]
----

Alternatively, it is possible to use a _local repository_, in which case you can specify the path to the repository:

.Using a local repository
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=specify-metadata-repository-file]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=specify-metadata-repository-file]
----

=== Configuring the metadata repository

Once activated, for each library included in the native image, the plugin will automatically search for GraalVM reachability metadata in the repository.
In some cases, you may need to exclude a particular module from the search.
This can be done by adding it to the exclude list:

.Excluding a module from search
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=exclude-module-from-metadata-repo]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=exclude-module-from-metadata-repo]
----

Last, it is possible for you to override the _metadata version_ of a particular module.
This may be interesting if there's no specific metadata available for the particular version of the library that you use, but that you know that a version works:

.Specifying the metadata version to use for a particular library
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=specify-metadata-version-for-library]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=specify-metadata-version-for-library]
----

[[plugin-configurations]]
== Configurations defined by the plugin

For each binary (`main` and `test`), the plugin declares 2 configurations that users or plugin authors can use to tweak the native image compilation classpath:

- `nativeImageCompileOnly` (for the `main` binary) and `nativeImageTestCompileOnly` (for the `test` binary) can be used to declare dependencies which are only needed at image compilation.
- `nativeImageClasspath` (for the `main` binary) and `nativeImageTestClasspath` (for the `test` binary) are the configurations which are resolved to determine the image classpaths.

The native image "compile only" configurations can typically be used to declare dependencies which are only required when building a native binary, and therefore shouldn't leak to the classic "JVM" runtime.

For example, you could declare a source set which uses the GraalVM SDK to implement native features.
This source set would contain code which is only relevant to native images building:

.Declaring a custom source set
[source, groovy, role="multi-language-sample"]
----
include::../../../../samples/java-application-with-extra-sourceset/build.gradle[tag=extra-sourceset]
----

[source, kotlin, role="multi-language-sample"]
----
include::../../../../samples/java-application-with-extra-sourceset/build.gradle.kts[tag=extra-sourceset]
----

== Javadocs

In addition, you can consult the link:javadocs/native-gradle-plugin/index.html[Javadocs of the plugin].
