= Gradle plugin for GraalVM Native Image building
The GraalVM team
:highlighjsdir: {gradle-relative-srcdir}/highlight

image:https://github.com/graalvm/native-build-tools/actions/workflows/test-native-gradle-plugin.yml/badge.svg[]

== Introduction

The {doctitle} adds support for building and testing native images using the https://gradle.org[Gradle build tool].

For upgrading please take a look at the <<index.adoc#changelog,Changelog>>.

[[quickstart]]
== Quickstart

====
<<gradle-plugin-quickstart.adoc#,Getting Started with Gradle Plugin for GraalVM Native Image>>
====

====
You can find full samples in https://github.com/graalvm/native-build-tools/tree/master/samples[the source repository].
====

====
The plugin requires that you https://www.graalvm.org/latest/docs/getting-started/[setup GraalVM].

The easiest way to install GraalVM is to use the https://sdkman.io/jdks[SDKMAN!].

For other installation options, go to https://www.graalvm.org/downloads/[GraalVM Downloads].
====

== Reference documentation

=== Adding the plugin

Add following to `plugins` section of your project's `build.gradle` / `build.gradle.kts`:

.Applying the plugin
[source,groovy,subs="verbatim,attributes", role="multi-language-sample"]
----
plugins {
  // ...

  // Apply GraalVM Native Image plugin
  id 'org.graalvm.buildtools.native' version '{gradle-plugin-version}'
}
----

[source,kotlin,subs="verbatim,attributes",role="multi-language-sample"]
----
plugins {
  // ...

  // Apply GraalVM Native Image plugin
  id("org.graalvm.buildtools.native") version "{gradle-plugin-version}"
}
----

NOTE: This plugin supplements and heavily relies on regular Java plugins (e.g. `application`, `java-library`, `java` etc). Not having them included in your project will most probably cause errors.

[TIP]
.Testing pre-releases
====
You can use development versions of the plugin by adding our snapshot repository instead. Pre-releases are provided for convenience, without any guarantee.
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/settings.gradle[tags=pre-release, indent=0]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/settings.gradle.kts[tags=pre-release, indent=0]
----
====

=== Installing GraalVM Native Image tool

By default, the plugin will try to use the `native-image` tool that is bundled with the JDK that is used to run Gradle.
This means you must make sure that you run Gradle with a GraalVM JDK.

Alternatively, you may choose to:

1. Set up a `GRAALVM_HOME` environment variable pointing to your GraalVM installation, in which case the JDK pointed at this location will be used for Native Image builds instead
2. <<configuration-toolchains-enabling, Enable toolchain support>>

[[configuration]]
== Configuration

This plugin works with the `application` plugin and will register a number of tasks and extensions for you to configure.

=== Available tasks

The main tasks that you will want to execute are:

- `nativeCompile`, which will trigger the generation of a native executable of your application
- `nativeRun`, which executes the generated native executable
- `nativeTestCompile`, which will build a native image with tests found in the `test` source set
- `nativeTest`, which will <<testing-support,execute tests>> found in the `test` source set in native mode

Those tasks are configured with reasonable defaults using the `graalvmNative` extension `binaries` container of type link:javadocs/native-gradle-plugin/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.html[NativeImageOptions].

The main executable is configured by the image named `main`, while the test executable is configured via the image named `test`.

=== Native image options

The link:javadocs/native-gradle-plugin/org/graalvm/buildtools/gradle/dsl/NativeImageOptions.html[NativeImageOptions] allows you to tweak how the native image is going to be built.
The plugin allows configuring the final binary, the <<test-binary-config,tests>> one, as well as apply options to both.

[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=configure-binaries]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=configure-binaries]
----

[[configuration-toolchains]]
=== Using Gradle toolchains

[[configuration-toolchains-enabling]]
==== Enabling toolchain detection

Instead of relying on the JDK which is used to run Gradle, you can use the https://docs.gradle.org/current/userguide/toolchains.html[Gradle toolchain support] to select a specific GraalVM installation.

However, because of limitations in Gradle, the plugin may not be able to properly detect the toolchain.
In particular, this will only work properly if you _only_ have GraalVM JDKs installed on the machine: **Otherwise, Gradle will not be able to reliably detect GraalVM JDKs**, nor detect GraalVM distributions from different vendors.

Should you still want to enable toolchain support, you do it via the `graalvmNative` extension:

.Enabling toolchain detection
[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=enabling-toolchain, indent=0]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=enabling-toolchain, indent=0]
----

==== Selecting the GraalVM toolchain

By default, the plugin will select a Java 11 GraalVM toolchain using the vendor string `GraalVM`,
which works properly for GraalVM up to version 22.3 included.
More recent versions of GraalVM do not have a specific version and are aligned with the language version they support.

If you want to use a different toolchain, for example a distribution compatible with Java 20 from Oracle, you can configure the toolchain like this:

.Selecting the GraalVM toolchain
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=select-toolchain]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=select-toolchain]
----

Again, be aware that the toolchain detection _cannot_ distinguish between GraalVM JDKs and standard JDKs without Native Image support: if you have both installed on the machine, Gradle may randomly pick one or the other.

[[configuration-options]]
==== Configuration options

The following configuration options are available for building images:

.NativeImageOption configuration
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=all-config-options]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=all-config-options]
----

NOTE: For options that can be set using command-line, if both DSL and command-line options are present, command-line options take precedence.

[[max_parallel_builds]]
==== Max parallel builds

When using Gradle parallel builds, the plugin will automatically limit the number of native images which can be built concurrently, in order to limit CPU and memory usage.
By default, it's limited to the number of CPU cores / 16, but you can change this limit either by setting the `org.graalvm.buildtools.max.parallel.builds` gradle property (e.g in your `gradle.properties` file) or by setting the `GRAALVM_BUILDTOOLS_MAX_PARALLEL_BUILDS` environment variable.

[[configuration-advanced]]

[[long_classpath_and_fat_jar_support]]
==== Long classpath, @argument file and fat jar support

Since release 0.9.10, the plugin will automatically pass arguments to the `native-image` tool using an argument file, which should prevent all https://github.com/graalvm/native-build-tools/issues/85[long classpath issues] under Windows.
However, if you are using an older GraalVM release (older than 21.3) which doesn't support argument files, you will need to rely on creating a "fat jar", which includes all entries from the classpath automatically, to workaround the problem:

.Enabling the fat jar creation
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=enable-fatjar]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=enable-fatjar]
----

Alternatively, it is possible to use your own fat jar (for example created using the https://imperceptiblethoughts.com/shadow/[Shadow plugin]) by setting the `classpathJar` property directly on the _task_:

.Enabling a custom fat jar creation
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=custom-fatjar]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=custom-fatjar]
----

When the `classpathJar` property is set, the `classpath` property is _ignored_.

[[testing-support]]
== Testing support

This plugin supports running tests on the
https://junit.org/junit5/docs/current/user-guide/[JUnit Platform] as native images. This
means that tests will be compiled and executed as native code.

NOTE: The minimum supported version is JUnit 5.8.1 (JUnit Platform 1.8.1, JUnit Jupiter 5.8.1, JUnit Vintage 5.8.1)

In theory, any `TestEngine` supported on the JUnit Platform should be supported by this
plugin as long as the programming language used by the `TestEngine` and the programming
language used to write the tests is supported in a GraalVM native image. This plugin
provides explicit support for the JUnit Jupiter and JUnit Vintage test engines, and
support for additional test engines should be possible with custom native configuration.

Currently, this feature requires the execution of the tests in the classic "JVM" mode _prior to_ the execution of tests in native mode. To execute the tests, execute:

[source,bash]
----
./gradlew nativeTest
----

[[test-binary-config]]
=== Configuring test image options

You can fine-tune the test binary using the `test` binary configuration.
The following example prints additional data for troubleshooting and sets the minimal optimizations.

[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=configure-test-binary]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=configure-test-binary]
----

[[testing-support-disabling]]
=== Disabling testing support

There are cases where you might want to disable native testing support:

- You don't actually want to run your tests in native mode.
- Your library or application uses a testing framework that is not supported on the JUnit
  Platform.
- You need to use the <<agent-support, agent>> when running tests on the JVM but do not
  wish to run those same tests in native mode.

In this case, you can disable native testing support by configuring the `graalvmNative`
extension as follows:

.Disabling testing support
[source,groovy,role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=disable-test-support]
----

[source,kotlin,role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=disable-test-support]
----

[[extra-test-suites]]
=== Configuring additional test suites

It's common to have multiple test source sets in a Gradle build.
Typically, you may have an integration test suite, or a functional test suite, in addition to the unit test suite.
The plugin supports running those tests as native binaries too.

For example, imagine that you have a source set named `integTest` and that its corresponding test task is named `integTest`.
In this case you can register a new native test binary via the `graalvmNative` extension:

.Registering a new test suite
[source, groovy, role="multi-language-sample"]
----
include::../../../../samples/java-application-with-custom-tests/build.gradle[tag=register-native-test]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=custom-binary]
----

The plugin will then automatically create the following tasks:

- `nativeIntegTestCompile`, to compile a native image using the `integTest` source set
- `nativeIntegTest`, to execute the tests in native mode

The same mechanism can be used if you have multiple test tasks for a single test source set, which is often the case with manual test sharding.

[[agent-support]]
== Reflection support and running with the native agent

If your project requires reflection, classpath resources, dynamic proxies or other features requiring explicit native configuration, it may prove helpful to first run your application or tests using the https://www.graalvm.org/reference-manual/native-image/metadata/AutomaticMetadataCollection/[`native-image-agent`].

The Native Image Gradle plugin simplifies generation of the required metadata files by injecting the agent automatically for you (this includes, but is not limited to the reflection file).

Any task that extends `JavaForkOptions` (like `test`, `run` etc) can be instrumented by passing `-Pagent` to gradle when running said tasks.

The agent can run in multiple modes that dictate how the metadata is collected and merged.

Once the metadata is collected, it can be copied into the project using the `metadataCopy` task.

[source,bash]
----
./gradlew -Pagent run # Runs on JVM with native-image-agent.
./gradlew metadataCopy --task run --dir src/main/resources/META-INF/native-image # Copies the metadata collected by the agent into the project sources
./gradlew nativeCompile # Builds image using metadata acquired by the agent.

# For testing
./gradlew -Pagent nativeTest # Runs on JVM with the native-image agent, collects the metadata and uses it for testing on native-image.
----

The agent can run in multiple modes:

* Standard - Collects metadata without conditions. This is recommended if you are building an executable.
* Conditional - Collects metadata with conditions. This is recommended if you are creating conditional metadata for a library intended for further use.
* Direct - For advanced users only. This mode allows directly controlling the command line passed to the agent.

The default mode is specified in the DSL but can be changed by passing the mode name to Gradle when using the agent: `-Pagent=conditional`

The generated configuration files will be found in the `${buildDir}/native/agent-output/${taskName}` directory, for example, `build/native/agent-output/run`.
The plugin will also substitute `{output_dir}` in the agent options to point to this directory during the agent run.

[[agent-support-configuring-options]]
=== Configuring agent options

The native agent can be configured https://www.graalvm.org/reference-manual/native-image/Agent/[with additional options].
This can be done using the `agent` configuration block.
Each agent option has a corresponding field in the DSL.
See <<configuration-options>> for the full list of available options.


[[metadata-support]]
== GraalVM Reachability Metadata Support

Since release 0.9.11, the plugin adds experimental support for the https://github.com/oracle/graalvm-reachability-metadata/[GraalVM reachability metadata repository].
This repository provides https://www.graalvm.org/22.2/reference-manual/native-image/ReachabilityMetadata/[reachability metadata] for libraries that do not support GraalVM Native Image.

NOTE: This version of the plugin defaults to the using the metadata repository in version {metadata-repository-version}. There is nothing for you to configure if you are fine with this version. The repository is also published on Maven Central at the following coordinates: `org.graalvm.buildtools:graalvm-reachability-metadata:graalvm-reachability-metadata` with the `repository` classifier and `zip` extension, e.g. `graalvm-reachability-metadata-{gradle-plugin-version}-repository.zip`.

=== Configuring the metadata repository

Metadata repository is enabled by default. Support can be disabled explicitly:

.Disabling the metadata repository
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=disable-metadata-repository]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=enable-metadata-repository]
----

A metadata repository consists of configuration files for GraalVM.
The plugin will automatically download the configuration metadata from the official repository if you supply the version of the repository you want to use:

.Overriding the repository version
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=specify-metadata-repository-version]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=specify-metadata-repository-version]
----

Alternatively, it is possible to use a _local repository_, in which case you can specify the path to the repository:

.Using a local repository
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=specify-metadata-repository-file]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=specify-metadata-repository-file]
----

For each library included in the native image, the plugin will automatically search for GraalVM reachability metadata in the repository.
In some cases, you may need to exclude a particular module from the search.
This can be done by adding it to the exclude list:

.Excluding a module from search
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=exclude-module-from-metadata-repo]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=exclude-module-from-metadata-repo]
----

Last, it is possible for you to override the _metadata version_ of a particular module.
This may be interesting if there's no specific metadata available for the particular version of the library that you use, but that you know that a version works:

.Specifying the metadata version to use for a particular library
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=specify-metadata-version-for-library]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=specify-metadata-version-for-library]
----

=== Including metadata repository files

By default, reachability metadata will be used only when your native image is generated.
In some situations, you may want a copy of the reachability metadata to use directly.

For example, copying the reachability metadata into your jar can be useful when some other process is responsible for converting your jar into a native image.
You might be generating a shaded jar and using a https://paketo.io/[Paketo buildpack] to convert it to a native image.

To download a copy of the metadata into the `build/native-reachability-metadata` directory you can the `collectReachabilityMetadata` task.
Files will be downloaded into `META-INF/native-image/<groupId>/<versionId>` subdirectories.

To include metadata repository inside your jar you can link to the task using the `jar` DSL `from` directive:

.Including metadata repository files
[source, groovy, role="multi-language-sample"]
----
include::../snippets/gradle/groovy/build.gradle[tags=include-metadata]
----

[source, kotlin, role="multi-language-sample"]
----
include::../snippets/gradle/kotlin/build.gradle.kts[tags=include-metadata]
----

For more advanced configurations you can declare a `org.graalvm.buildtools.gradle.tasks.CollectReachabilityMetadata` task and set the appropriate properties.

[[pgo-support]]
== Profile-guided optimizations

The plugin supports building images with https://www.graalvm.org/latest/reference-manual/native-image/guides/optimize-native-executable-with-pgo/[Profile-Guided Optimizations].

It works in 3 phases:

- the first one consists in generating a binary with instrumentation enabled
- the second phase consists in running the binary in order to gather profiling information
- the third phase consists in compiling the binary with the generated profile

In order to generate a binary with instrumentation enabled, you should run the `nativeCompile` command with the `--pgo-instrument` command line option:

`./gradlew nativeCompile --pgo-instrument`

This will generate a binary under `build/native/nativeCompile` with the `-instrumented` suffix.
You can run the binary to gather profiling data:

[source,bash]
----
$ cd build/native/nativeCompile/
$ ./my-application-instrumented`
----

A `default.iprof` file will be generated once the application is stopped.
Alternatively, you can have Gradle both generate and run the instrumented binary in a single command by running:

`./gradlew nativeCompile --pgo-instrument nativeRun`

In which case the profile will automatically be stored into `build/native/nativeCompile`.

The last phase consists in copying the generated profile, so that it's automatically used when building the native binary.
The conventional location for profiles is `src/pgo-profiles/<name of the binary>`.
By default, we're using the `main` binary so the location will be `src/pgo-profiles/main`.
Copy the `default.iprof` file into that directory, then run:

`./gradlew nativeCompile`

The profile will automatically be used and the binary compiled with PGO.
It is possible to include more than one profile, in which case you should rename the `.iprof` files in the `src/pgo-profiles/main` directory.

[[plugin-configurations]]
== Configurations defined by the plugin

For each binary (`main` and `test`), the plugin declares 2 configurations that users or plugin authors can use to tweak the native image compilation classpath:

- `nativeImageCompileOnly` (for the `main` binary) and `nativeImageTestCompileOnly` (for the `test` binary) can be used to declare dependencies which are only needed at image compilation.
- `nativeImageClasspath` (for the `main` binary) and `nativeImageTestClasspath` (for the `test` binary) are the configurations which are resolved to determine the image classpaths.

The native image "compile only" configurations can typically be used to declare dependencies which are only required when building a native binary, and therefore shouldn't leak to the classic "JVM" runtime.

For example, you could declare a source set which uses the GraalVM SDK to implement native features.
This source set would contain code which is only relevant to native images building:

.Declaring a custom source set
[source, groovy, role="multi-language-sample"]
----
include::../../../../samples/java-application-with-extra-sourceset/build.gradle[tag=extra-sourceset]
----

[source, kotlin, role="multi-language-sample"]
----
include::../../../../samples/java-application-with-extra-sourceset/build.gradle.kts[tag=extra-sourceset]
----

== Javadocs

In addition, you can consult the link:javadocs/native-gradle-plugin/index.html[Javadocs of the plugin].
