= Native Build Tools
The GraalVM team

The {doctitle} project provides plugins for different build tools to add support for building and testing native applications written in Java
(or any other language compiled to JVM bytecode) using the https://www.graalvm.org/reference-manual/native-image/[GraalVM  Native Image].
At the moment, you can build your native projects using our Gradle or Maven plugin.

Each plugin takes metadata for available libraries from the https://github.com/oracle/graalvm-reachability-metadata[GraalVM reachability metadata repository]
to provide better experience during the development of your native project.

If you are using alternative build systems, see <<alternative-build-systems.adoc#,Useful Hints for Alternative Build Systems>>.

[discrete]
=== Documentation

In case you are new to the Native Build Tools (eiter as an end user or a library author), read our:

- <<gradle-plugin-quickstart.adoc#,Getting started with Gradle plugin>>
- <<maven-plugin-quickstart.adoc#,Getting started with Maven plugin>>

For detailed documentation, please refer to the following pages of the specific build tools:

- <<gradle-plugin.adoc#,The Gradle plugin documentation>>
- <<maven-plugin.adoc#,The Maven plugin documentation>>

You can see the full changelog <<changelog.adoc#,here>>.

[discrete]
=== Contributing

If you are interested in contributing or reporting an issue related to the plugins, please refer to the https://github.com/graalvm/native-build-tools[Native Build Tools repository].
Also, be aware that all contributors must sign the https://oca.opensource.oracle.com/[Oracle Contributor Agreement] (OCA).

[TIP]
--
Please be aware that this repository should be used to report issues related to the Maven or Gradle plugins for GraalVM.
Please report issues which are specific to the framework itself (for example https://spring.io/[Spring Framework] or the https://micronaut.io/[Micronaut framework]) to their specific repositories.
