= Native Build Tools
The GraalVM team

The {doctitle} project provides plugins for different build tools to add support for building and testing native applications written in Java (or any other language compiled to JVM bytecode).

Most notably, this is the official source for integrating with the https://www.graalvm.org/reference-manual/native-image/[GraalVM `native-image` tool].

Please refer to the following pages for build tool specific documentation:

- The <<gradle-plugin.adoc#,Gradle plugin documentation>>
- The <<maven-plugin.adoc#,Maven plugin documentation>>

If you are interested in contributing, please refer to our https://github.com/graalvm/native-build-tools[Git repository].

[[changelog]]
== Changelog
=== Release 0.9.12

==== Gradle plugin
* Completely reworked agent support - **BREAKING CHANGE**
* The agent block is no longer tied to the target binary.
* The agent can now instrument any task that extends `JavaForkOptions`.
* Introduced the `metadataCopy` task.
* Introduced the concept of agent modes.
** Under the hood, the agent mode dictates what options are passed to the agent and how metadata produced by multiple runs get merged.

=== Release 0.9.11

==== Maven plugin

* Fix long classpath issue under Windows when running native tests
* Inherit environment variables and system properties from the surefire plugin configuration when executing tests
* Fix invocation of `native-image` when classpath contains spaces

==== Gradle plugin

* Add support for environment variables in native test execution
* Fix invocation of `native-image` when classpath contains spaces
* Add experimental support for the JVM reachability metadata repository

=== Release 0.9.10

==== Maven plugin

* Native testing support can now be explicitly disabled via `skipNativeTests`.
   - See <<maven-plugin.adoc#testing-support-disabling, Disabling testing support>> for details.
* Fixed race condition which prevented the agent files to be generated properly if tests were executed concurrently
* Documented version compatibility for the JUnit Platform and Maven Surefire plugin.
   - See <<maven-plugin.adoc#testing-support-version-compatibility, Version compatibility>> for details.
* Add support for long classpath by using an argument file when invoking `native-image`

==== Gradle plugin

* Fixed `nativeRun` not working properly under Windows
* Fixed race condition which prevented the agent files to be generated properly if tests were executed concurrently
* Add support for long classpath by using an argument file when invoking `native-image`

=== Release 0.9.9

==== Gradle plugin

* Fixed resource inference not working on custom binaries
* Fixed `disableToolchainDetection` not working if a GraalVM installation isn't present. Please use `graalvmNative.toolchainDetection.set(false)` instead.

=== Release 0.9.8

==== Gradle plugin

* [Breaking change] The `agent` option has been replaced with an `agent { ... }` configuration block which includes an `enabled` property.
* Toolchain support can now be disabled altogether, which can be useful when using GraalVM Enterprise Edition.
  - See <<gradle-plugin.adoc#configuration-toolchains-disabling, Disabling toolchain detection>> for details.
* Fixed a bug when using a _fat jar_ which assumed that all entries to be repackaged were jars.
* Agent options are now configurable.
   - Note that the `experimental-class-loader-support` agent option is no longer added by default.
   - See <<gradle-plugin.adoc#agent-support-configuring-options, Configuring agent options>> for details.
* Added an option to perform resource detection in classpath entries which contain a `native-image/resource-config.json` file.

==== Maven plugin

* The agent can now be enabled in the POM.
  - See <<maven-plugin.adoc#agent-support-enabling, Enabling the agent>> for details.
* Agent options are now configurable.
   - Note that the `experimental-class-loader-support` agent option is no longer added by default.
   - See <<maven-plugin.adoc#agent-support-configuring-options, Configuring agent options>> for details.
* Added an option to perform resource detection in classpath entries which contain a `native-image/resource-config.json` file.

==== JUnit Platform Native

* Builds now correctly fail if a container-level extension or lifecycle method fails --
  for example, if an `@BeforeAll` method in a JUnit Jupiter test class throws an exception.
* Builds no longer fail when tests are aborted -- for example, via a failed assumption.
* Improved documentation for JUnit Platform and Maven Surefire support in the plugins.

=== Release 0.9.7.1

==== Bugfixes

- Fixed https://github.com/graalvm/native-build-tools/issues/144[Maven plugin configuration not applied if declared in a parent POM].

=== Release 0.9.7

Release didn't include any fixes.

=== Release 0.9.6

==== Upgrade to JUnit 5.8

The plugins now depend on JUnit 5.8 which provides an official test listener which is used by these plugins.
As a consequence, Maven users will have to configure their builds to enable the plugin extensions:

```xml
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
    <version>${native.maven.plugin.version}</version>
    <extensions>true</extensions>
    ...
</plugin>
```

The dependency on `junit-platform-native` which used to be required pre-0.9.6 can now safely be removed.

For Gradle users, there's no impact on the configuration, however a good consequence is that the `junit-native-platform` dependency no longer leaks into your application's classpath.

==== Agent support for Maven plugin

The Maven plugin now supports the GraalVM agent to generate configuration files.
Please refer to the <<maven-plugin.adoc#agent-support,Maven plugin documentation>> for details.

==== Disabling testing support

The Gradle plugin now provides an option to disable testing support.
This can be useful if the test framework you are using doesn't work with this plugin or that you simply don't want to execute tests natively.

To disable tests, use the `graalvmNative` configuration block:

```kotlin
graalvmNative {
    testSupport.set(false)
}
```

==== Configuring additional test images

The Gradle plugin now supports building multiple test images, which can be used to execute tests natively for more kinds of tests: integration tests, functional tests, ...

For more information, please refer to <<gradle-plugin.adoc#extra-test-suites,the Gradle plugin documentation>>

=== Release 0.9.5

This release contains, in preparation for supporting more images in the Gradle plugin:

- The `nativeBuild` and `nativeTest` extensions are now deprecated. A top-level container for configuring native images has been introduced. Instead of:

[source,groovy]
----
nativeBuild {
   verbose = true
}
----

you need to use:

[source,groovy]
----
graalvmNative {
  binaries {
    main {
      verbose = true
    }
  }
}
----

and instead of:

[source,groovy]
----
nativeTest {
    buildArgs("...")
}
----

you need to use:

[source,groovy]
----
graalvmNative {
  binaries {
    test {
      verbose = true
    }
  }
}
----

- The `nativeBuild` task has been renamed to `nativeCompile`.
- The `nativeTestBuild` task has been renamed to `nativeTestCompile`.

Both `nativeBuild` and `nativeTestBuild` task invocations are still supported but deprecated and will be removed in a future release.

=== Release 0.9.4

This release works around a limitation for Windows users who encounter an issue with long classpath entries on CLI: the Gradle plugin will now automatically handle this problem by creating a fat jar instead of passing all entries on classpath (this behavior can be <<gradle-plugin.adoc#long_classpath_and_fat_jar_support, disabled>>) if needed).
Maven users will have to <<maven-plugin.adoc#long_classpath_and_shading_support, configure their build differently>> to use shading.

In addition to this, we're now publishing development snapshots of this plugin. For Gradle, you will need to declare this repository in your settings.gradle(.kts) file:

[source,groovy]
----
pluginManagement {
    plugins {
        id 'org.graalvm.buildtools.native' version '0.9.5-SNAPSHOT'
    }
    repositories {
        maven {
            url "https://raw.githubusercontent.com/graalvm/native-build-tools/snapshots"
        }
        gradlePluginPortal()
    }
}
----

For Maven, you need to use this repository configuration:

[source,xml]
----
<pluginRepositories>
    <pluginRepository>
        <id>graalvm-native-build-tools-snapshots</id>
        <name>GraalVM native-build-tools Snapshots</name>
        <url>https://raw.githubusercontent.com/graalvm/native-build-tools/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
----

=== Release 0.9.3

This release contains:

- Fix for mainClass not being optional (Gradle plugin)
- Fix for Gradle < 7 failing to determine GraalVM toolchain
- Gradle plugin now registers proper groups
- Automatic native-image tool fetching via gu (Gradle plugin)
- FIxed issue where nativeTest would fail when tests are annotated with Timeout
- Added a sharedLibrary configuration option for Gradle plugin
- Removed broken server configuration option from Gradle plugin
- Added a documentation website with proper CI integration

In addition to those improvements, several behind-the-scenes changes were made:

- Introduced "Dockerless" Maven plugin functional testing
- Parallelized Gradle testing in CI
- Replaced groovy-json with jackson-databind for JSON handling
- Fixed Github Actions syntax to enable manual workflow invoking

=== Release 0.9.2

This release contains:

- Revamped Gradle plugin that is now a lot more idiomatic.
- Fixes for several issues regarding JUnit testing.
- Removal of Test Discovery mode from the Maven plugin.
- Fix for Maven creating empty test images when no tests are present.
- Added support for Kotlin tests in Gradle.

In addition to those improvements, several behind-the-scenes changes were made in order to ensure better compatibility moving forward:

- Test coverage has been greatly improved for all subprojects.
- Build tooling for this repository has been improved significantly.

Note that there has been a breaking change in the Gradle plugin - `persistConfig` configuration option was removed.
Using said option will cause existing builds to break, so users are advised to remove it from their configuration prior to upgrading.
System property `-DpersistConfig` will have no effect going forward.

=== Release 0.9.1

This release contains:

- Fixes for most of the known issues regarding Gradle and Maven plugins
- Massively improved automatic JUnit support as well as initial JUnit Vintage support
- Improved JavaDoc and tests for the Gradle plugin

=== Release 0.9.0

Initial release
