= Native Build Tools
The GraalVM team

The {doctitle} project provides plugins for various build tools, enabling support for building and testing native applications written in Java (or any other language compiled to JVM bytecode) using https://www.graalvm.org/reference-manual/native-image/[GraalVM  Native Image].
Currently, you can build your native applications using our Gradle or Maven plugins.

Each plugin takes metadata for available libraries from the https://github.com/oracle/graalvm-reachability-metadata[GraalVM reachability metadata repository]
to provide better experience during the development of your native project.

If you are using alternative build systems, see <<alternative-build-systems.adoc#,Useful Hints for Alternative Build Systems>>.

[discrete]
=== Documentation

If you're new to the Native Build Tools, whether as an end user or a library author, check out our:

- <<end-to-end-gradle-guide.adoc#,Building Native Images with Maven: An End-to-End Guide>>
- <<end-to-end-maven-guide.adoc#,Building Native Images with Gradle: An End-to-End Guide>>

For detailed documentation, see the corresponding page for each build tool:

- <<gradle-plugin.adoc#,Gradle plugin documentation>>
- <<maven-plugin.adoc#,Maven plugin documentation>>

For updates to the Native Build Tools between releases, see the full changelog <<changelog.adoc#,here>>.

[discrete]
=== Contributing

If you are interested in contributing or reporting an issue related to the plugins, please refer to the https://github.com/graalvm/native-build-tools[Native Build Tools repository].
Please note that all contributors must sign the https://oca.opensource.oracle.com/[Oracle Contributor Agreement] (OCA).

[TIP]
--
This repository should be used for reporting issues related specifically to the Maven or Gradle plugins for GraalVM Native Image.
For issues related to frameworks such as https://spring.io/[Spring Framework] or https://micronaut.io/[Micronaut framework], please report them to their respective repositories.
