= Maven plugin for GraalVM Native Image building
The GraalVM team
:highlighjsdir: {gradle-relative-srcdir}/highlight

image:https://github.com/graalvm/native-image-build-tools/actions/workflows/native-maven-plugin.yml/badge.svg[]

[[introduction]]
== Introduction

The {doctitle} adds support for building and testing native images using https://maven.apache.org[Apache Maven]™.

For upgrading please take a look at the <<index.adoc#changelog,Changelog>>.

[[quickstart]]
== Quickstart

This plugin first requires that you <<graalvm-setup.adoc#,setup GraalVM and `native-image` properly>>.
It will then make use of Maven profiles to enable building and testing of native images.

[[configuration]]
== Configuration

[[configuration-registering-plugin]]
=== Registering the plugin

Add the following profile to your `pom.xml` file to register the `native-maven-plugin`.

```xml
  <profiles>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>${native.maven.plugin.version}</version>
            <extensions>true</extensions>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>build</goal>
                </goals>
                <phase>package</phase>
              </execution>
              <execution>
                <id>test-native</id>
                <goals>
                  <goal>test</goal>
                </goals>
                <phase>test</phase>
              </execution>
            </executions>
            <configuration>
              <!-- ... -->
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

You can then build a native executable directly with Maven using the `mvn -Pnative -DskipTests package` command without running the `native-image` command as a separate step.

The plugin figures out which JAR files it needs to pass to the native image and
what the executable main class should be.
If the heuristics fail with the `no main manifest attribute, in target/<name>.jar` error, the main class should be
specified in the `<configuration>` node of the plugin.
When `mvn -Pnative package` completes, an executable is ready for use, generated in the `target` directory of the project.

[TIP]
.Testing pre-releases
====
You can use development versions of the plugin by adding our snapshot repository. Pre-releases are provided for convenience, without any guarantee.
[source,xml]
----
<pluginRepositories>
    <pluginRepository>
        <id>graalvm-native-build-tools-snapshots</id>
        <name>GraalVM native-build-tools Snapshots</name>
        <url>https://raw.githubusercontent.com/graalvm/native-build-tools/snapshots</url>
        <releases>
            <enabled>false</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </pluginRepository>
</pluginRepositories>
----
====

[[configuration-options]]
=== Configuration options

If you use Native Image Maven plugin, it will pick up all the configuration for your application stored below the `META-INF/native-image/` resource location, as described in https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/[Native Image Build Configuration].
It is also possible to customize the plugin within a
`<configuration>` node. The following configuration options are available.

`<mainClass>`::
   If the execution fails with the `no main manifest attribute, in target/<name>.jar`
   error, the main class should be specified. By default the plugin consults several
   locations in the `pom.xml` file in the following order to determine what the main class
   of the image should be.
      * `<maven-shade-plugin> <transformers> <transformer> <mainClass>`
      * `<maven-assembly-plugin> <archive> <manifest> <mainClass>`
      * `<maven-jar-plugin> <archive> <manifest> <mainClass>`
`<imageName>`::
   Use `<imageName>` to set a custom filename for the generated native image. If a custom
   image name is not supplied, the artifact ID of the project will be used by default.
`<buildArgs>`::
   If you want to pass additional arguments to the native image builder, use `<buildArgs>`
   in the configuration of the plugin.
`<skipNativeBuild>`::
   To skip generation of the native image, supply
   `<skipNativeBuild>true</skipNativeBuild>` in the configuration of the plugin.

For example, to build a native image named `executable-name` that uses
`org.example.ClassName` as its main class with assertions enabled, add the following
`<configuration>` block for the `native-maven-plugin`.

```xml
<configuration>
  <imageName>executable-name</imageName>
  <mainClass>org.example.ClassName</mainClass>
  <buildArgs>
    <buildArg>--no-fallback</buildArg>
  </buildArgs>
</configuration>
```
[[configuration-options-agent-enabled]]
`<agent>` -> `<enabled>`::
   To enable the agent by default specify `<enabled>true</enabled>` as follows. The agent
   can also be enabled or disabled via the command line. See <<agent-support-enabling>>
   for details.
+
```xml
<configuration>
  <agent>
    <enabled>true</enabled>
  </agent>
</configuration>
```
[[configuration-options-agent-options]]
`<agent>` -> `<options>`::
   If you would like to configure the options for the agent (see <<agent-support>>) --
   for example, to configure experimental features such as `experimental-class-loader-support`
   or advanced features such as
   https://www.graalvm.org/reference-manual/native-image/Agent/#caller-based-filters[Caller-based Filters]
   and https://www.graalvm.org/reference-manual/native-image/Agent/#access-filters[Access Filters] --
   you can include `<options>` within the `<agent>` block.
     * You can supply multiple sets of `<options>`.
     * You may declare one unnamed `<options>` element which will always be used whenever
       the agent is enabled. This should be used to share common options.
     * Additional `<options>` elements must declare a unique `name` attribute.
     * To enable a specific set of named `<options>`, supply `-DagentOptions=<NAME>` as a
       command-line argument for Maven, where `<NAME>` corresponds to the `name` attribute
       of the `<options>` element.
     * If `-DagentOptions=<NAME>` is not specified, named sets of options will not be used
       with the agent.
     * The Native Image Maven plugin automatically configures the `config-output-dir` for
       the agent. An attempt to provide a custom value for the `config-output-dir` option
       will therefore result in a build failure.
     * The following example demonstrates how to configure three sets of `<options>`, an
       unnamed set that is always active, one for application execution (`main`) and one
       for tests (`test`). The names `main` and `test` are for demonstration purposes
       only: you may choose any names you wish.
+
[source,xml,indent=0]
include::../../../../samples/java-application-with-reflection/pom.xml[tag=native-plugin-agent-options]

NOTE: If you use GraalVM Enterprise as the `JAVA_HOME` environment, the plugin builds a native image with enterprise features enabled -- for example, an executable will automatically be built with https://medium.com/graalvm/isolates-and-compressed-references-more-flexible-and-efficient-memory-management-for-graalvm-a044cc50b67e[compressed references] and other optimizations enabled.

[[configuration-reusing-config-from-parent]]
==== Reusing configuration from a parent POM

The `<buildArgs>` element can be combined between parent and children POMs. Suppose you have the following parent POM definition:

```xml
<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <version>${current_plugin_version}</version>
  <configuration>
    <imageName>${project.artifactId}</imageName>
    <mainClass>${exec.mainClass}</mainClass>
    <buildArgs>
      <buildArg>--no-fallback<buildArg>
    </buildArgs>
  </configuration>
</plugin>
```

Children projects have the ability to append `<buildArg>` arguments in the following way:

```xml
<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <configuration>
    <buildArgs combine.children="append">
      <buildArg>--verbose</buildArg>
    </buildArgs>
  </configuration>
</plugin>
```

In this case, the arguments that will be passed to the `native-image` executable will be:
```shell
--no-fallback --verbose
```

[[testing-support]]
== Testing support

This plugin supports running tests on the
https://junit.org/junit5/docs/current/user-guide/[JUnit Platform] as native images. This
means that tests will be compiled and executed as native code.

In theory, any `TestEngine` supported on the JUnit Platform should be supported by this
plugin as long as the programming language used by the `TestEngine` and the programming
language used to write the tests is supported in a GraalVM native image. This plugin
provides explicit support for the JUnit Jupiter and JUnit Vintage test engines, and
support for additional test engines should be possible with custom native configuration.

In order to use the recommended JUnit Platform test listener mode, you need to enable
extensions for the `native-maven-plugin` by adding `<extensions>true</extensions>` as follows.

[source,xml,indent=0]
include::../../../../samples/java-application-with-tests/pom.xml[tag=native-plugin-extensions]

Running `mvn -Pnative test` will then build and run native tests.

NOTE: This plugin requires JUnit Platform 1.8 or higher.

NOTE: This plugin provides integration with Maven Surefire 2.22.0 or higher.

[[long_classpath_and_shading_support]]
== Long classpath and shading support

Under Windows, https://github.com/graalvm/native-build-tools/issues/85[it is possible that the length of the classpath exceeds what the operating system supports] when invoking the CLI to build a native image.

If this happens, one option is to use a https://maven.apache.org/plugins/maven-shade-plugin[shaded jar] and use it instead of individual jars on classpath.

First, you'll need to setup the https://maven.apache.org/plugins/maven-shade-plugin[Maven Shade plugin]:

[source,xml,indent=0]
include::../../../../samples/java-application/pom.xml[tag=shade-plugin]

If you need testing support, add the JUnit Platform Native dependency explicitly:

[source,xml,indent=0]
include::../../../../samples/java-application-with-tests/pom.xml[tag=junit-platform-native-dependency]

Then the native plugin needs to be configured to use this jar instead of the full classpath:

[source,xml,indent=0]
include::../../../../samples/java-application/pom.xml[tag=native-plugin]


Depending on the other plugins your build uses (typically the Spring Boot plugin), you might have to configure, in addition, the main class:

[source,xml]
----
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
	<artifactId>native-maven-plugin</artifactId>
	<version>${native.buildtools.version}</version>
	<configuration>
		<imageName>${project.artifactId}</imageName>
		<mainClass>${exec.mainClass}</mainClass>
		<buildArgs>
			<buildArg>--no-fallback</buildArg>
		</buildArgs>
		<classpath>
			<param>
				${project.build.directory}/${project.artifactId}-${project.version}-shaded.jar
			</param>
		</classpath>
...
----


To be able to <<testing-support,execute tests in native mode>>, you will need more setup:

- Create a `src/assembly/test-jar-with-dependencies.xml` file with the following contents:

[source,xml,indent=0]
include::../../../../samples/java-application-with-tests/src/assembly/test-jar-with-dependencies.xml[tag=assembly]

- Add the assembly plugin to your `native` profile:

[source,xml,indent=0]
include::../../../../samples/java-application-with-tests/pom.xml[tag=assembly-plugin]

- Due to a limitation in Maven, you will need to move the tests execution to the "integration-test" phase:

[source,xml,indent=0]
include::../../../../samples/java-application-with-tests/pom.xml[tag=native-plugin]

Finally, you will need to execute tests using the `integration-test` phase instead of `test`:

```bash
./mvn -Pnative integration-test
```

Please refer to the https://maven.apache.org/plugins/maven-shade-plugin[Maven Shade plugin documentation] for more details on how to configure shading and the https://maven.apache.org/plugins/maven-assembly-plugin[Maven Assembly plugin documentation] to tweak what to include in tests.

[[agent-support]]
== Reflection support and running with the native agent

If your project requires reflection, classpath resources, dynamic proxies or other features requiring explicit native configuration, it may prove helpful to first run your application or tests using the https://www.graalvm.org/reference-manual/native-image/Agent/[`native-image-agent`].

The Native Image Maven plugin simplifies generation of the required configuration files by injecting the agent automatically for you (this includes, but is not limited to the reflection file).

The agent generates the native configuration files in a subdirectory of `target/native/agent-output`. Although those files will be automatically used if you run your build with the agent enabled, you should consider reviewing the generated files and adding them to your sources instead.

[[agent-support-enabling]]
==== Enabling the agent

The agent is disabled by default, but it can be enabled within your `pom.xml` file or via the command line.

The documentation for <<configuration-options-agent-enabled, agent configuration>> demonstrates how to enable the agent within your POM.

To enable the agent via the command line, supply the `-Dagent=true` flag when running Maven. The examples in the following sections demonstrate how to do this for your application and for tests.

[TIP]
====
If you have enabled the agent within your POM, you can still disable it via the command line by supplying the `-Dagent=false` flag.
====

[[agent-support-running-tests]]
=== Running tests with the agent

The simplest way to use the agent is to do it via execution of your tests.

Run your test suite with:

```bash
mvn -Pnative -Dagent=true test
```

When the `agent` system property is set to `true`, the agent will be automatically attached to your Maven Surefire test execution, and the generated files can be found in the `target/native/agent-output/test` directory.

To run your tests with custom agent options, supply the `-DagentOptions=<NAME>` command-line argument to Maven as follows. See the documentation for <<configuration-options-agent-options, agent options>> for details.

```bash
mvn -Pnative -Dagent=true -DagentOptions=test test
```

WARNING: If the agent is enabled, the `--allow-incomplete-classpath` option is automatically added to your native build options.

[[agent-support-running-application]]
=== Running your application with the agent

Executing your application with the agent is more involved and requires you to configure a separate mojo execution which allows forking the Java process.

In your `native` Maven profile section, add the following:

[source,xml,indent=0]
include::../../../../samples/java-application-with-reflection/pom.xml[tag=java-agent-exec]

Then you can execute your application with the agent by running:

```bash
mvn -Pnative -Dagent=true -DskipTests=true -DskipNativeBuild=true package exec:exec@java-agent
```

To execute your application with custom agent options, supply the `-DagentOptions=<NAME>` command-line argument to Maven as follows. See the To execute your application with custom agent options, supply the `-DagentOptions=<NAME>` command-line argument to Maven as follows. See the documentation for <<configuration-options-agent-options, agent options>> for details.

```bash
mvn -Pnative -Dagent=true -DagentOptions=main -DskipTests=true -DskipNativeBuild=true package exec:exec@java-agent
```

Both of the above commands will generate configuration files in the `target/native/agent-output/exec` directory.
If you want to run your native application with those configuration files, you then need to execute the following command:

```bash
mvn -Pnative -Dagent=true -DskipTests=true package exec:exec@native
```

WARNING: If the agent is enabled, the `--allow-incomplete-classpath` option is automatically added to your native build options.

[[javadocs]]
== Javadocs

In addition, you can consult the link:javadocs/native-maven-plugin/index.html[Javadocs of the plugin].
