= Maven plugin for GraalVM Native Image building
The GraalVM team
:highlighjsdir: {gradle-relative-srcdir}/highlight

image:https://github.com/graalvm/native-image-build-tools/actions/workflows/native-maven-plugin.yml/badge.svg[]

== Introduction

The {doctitle} adds support for building and testing native images using https://maven.apache.org[Apache Maven]™.

== Quickstart

This plugin first requires that you <<graalvm-setup.adoc#,setup GraalVM and `native-image` properly>>.
It will then make use of Maven profiles to enable building and testing of native images.

== Configuration

=== Registering the plugin

Add the following profile to your `pom.xml` file:

```xml
  <profiles>
    <profile>
      <id>native</id>
      <build>
        <plugins>
          <plugin>
            <groupId>org.graalvm.buildtools</groupId>
            <artifactId>native-maven-plugin</artifactId>
            <version>${native.maven.plugin.version}</version>
            <executions>
              <execution>
                <id>build-native</id>
                <goals>
                  <goal>build</goal>
                </goals>
                <phase>package</phase>
              </execution>
              <execution>
                <id>test-native</id>
                <goals>
                  <goal>test</goal>
                </goals>
                <phase>test</phase>
              </execution>
            </executions>
            <configuration>
              <!-- ... -->
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

You can then build a native executable directly with Maven using the `mvn -Pnative -DskipTests package` command without running the `native-image` command as a separate step.

The plugin figures out which JAR files it needs to pass to the native image and
what the executable main class should be.
If the heuristics fails with the `no main manifest attribute, in target/<name>.jar` error, the main class should be
specified in the `<configuration>` node of the plugin.
When `mvn -Pnative package` completes, an executable is ready for use, generated in the `target` directory of the project.

=== Configuration options

If you use Native Image Maven plugin, it will pick up all the configuration for your application stored below the  _META-INF/native-image/_ resource location, as described in https://www.graalvm.org/reference-manual/native-image/BuildConfiguration/[Native Image Build Configuration].
It is also possible to customize the plugin within a
`<configuration>` node. The following configurations are available.

1. Configuration parameter `<mainClass>`: if the execution fails with the `no main manifest attribute, in target/<name>.jar` error, the main class should be specified. By default the plugin consults several locations in the  `pom.xml` file in the following order to determine what the main class of the image should be:
* `<maven-shade-plugin> <transformers> <transformer> <mainClass>`
* `<maven-assembly-plugin> <archive> <manifest> <mainClass>`
* `<maven-jar-plugin> <archive> <manifest> <mainClass>`
2. Configuration parameter `<imageName>`: if an image filename is not set explicitly, use parameter `<imageName>` to provide a custom filename for the image.
3. Configuration parameter `<buildArgs>`: if you want to pass additional options for to the native image builder, use the `<buildArgs>` parameter in the definition of the plugin. For example, to build a native image with assertions enabled that uses _com.test.classname_ as a main class, add:

```xml
<configuration>
  <imageName>executable-name</imageName>
  <mainClass>com.test.classname</mainClass>
  <buildArgs>
    <buildArg>--no-fallback</buildArg>
  </buildArgs>
  <skip>false</skip>
</configuration>
```

If you use GraalVM Enterprise as the `JAVA_HOME` environment, the plugin builds a native image with Enterprise features enabled, e.g., an executable will automatically be built with https://medium.com/graalvm/isolates-and-compressed-references-more-flexible-and-efficient-memory-management-for-graalvm-a044cc50b67e[compressed references] and other optimizations enabled.

==== Reusing configuration from a parent POM

The `<buildArgs>` element can be combined between parent and children POM. Suppose the following parent POM definition:

```xml
<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <version>${current_plugin_version}</version>
  <configuration>
    <imageName>${project.artifactId}</imageName>
    <mainClass>${exec.mainClass}</mainClass>
    <buildArgs>
      <buildArg>--no-fallback<buildArg>
    </buildArgs>
  </configuration>
</plugin>
```

Children projects have the ability to append `<buildArg>` arguments in the following way:

```xml
<plugin>
  <groupId>org.graalvm.buildtools</groupId>
  <artifactId>native-maven-plugin</artifactId>
  <configuration>
    <buildArgs combine.children="append">
      <buildArg>--verbose</buildArg>
    </buildArgs>
  </configuration>
</plugin>
```

In this case, the arguments that will be passed to the `native-image` executable will be:
```shell
--no-fallback --verbose
```

== JUnit Testing support

In order to use the recommended test listener mode, you need to add following dependency:

```xml
<dependencies>
   <!-- ... -->
   <dependency>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>junit-platform-native</artifactId>
    <version>${current-junit-platform-native-version}</version>
    <scope>test</scope>
  </dependency>
</dependencies>
```

This step won't be needed as of JUnit 5.8 with a future release of native-maven-plugin (see the https://github.com/junit-team/junit5/issues/2619[related issue] for more information).

Running `mvn -Pnative -Dskip test` will then build and run native tests.

== Long classpath and shading support

Under Windows, https://github.com/graalvm/native-build-tools/issues/85[it is possible that the length of the classpath exceeds what the operating system supports] when invoking the CLI to build a native image.

If this happens, one option is to use a https://maven.apache.org/plugins/maven-shade-plugin[shaded jar] and use it instead of individual jars on classpath.

First, you'll need to setup the https://maven.apache.org/plugins/maven-shade-plugin[Maven Shade plugin]:

[source,xml,indent=0]
include::../../../../samples/java-application/pom.xml[tag=shade-plugin]

Then the native plugin needs to be configured to use this jar instead of the full classpath:

[source,xml,indent=0]
include::../../../../samples/java-application/pom.xml[tag=native-plugin]

Please refer to the https://maven.apache.org/plugins/maven-shade-plugin[Maven Shade plugin documentation] for more details on how to configure shading.

== Javadocs

In addition, you can consult the link:javadocs/native-maven-plugin/index.html[Javadocs of the plugin].
