name: '🔧 Prepare environment'
description: 'Prepare the environment for testing'

inputs:
  github-token:
    description: 'secrets.GITHUB_TOKEN'
    required: false
    default: ''
  java-version:
    description: 'Java version to use'
    required: false
    default: '17.0.12'
  graal-java-version:
    description: 'GraalVM Java version to use for tests (sets GRAALVM_HOME, leaves JAVA_HOME unchanged)'
    required: false
    default: '21'
  push-access:
    description: 'Does this workflow require push access?'
    required: false
    default: '0'
  ssh-key:
    description: 'secrets.SSH_PRIVATE_KEY'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: "🔧 Install Gradle JDK (JDK${{ inputs.java-version }})"
      uses: actions/setup-java@v4
      with:
        distribution: 'graalvm'
        java-version: ${{ inputs.java-version }}
    - name: "🔧 Install GraalVM for tests (JDK${{ inputs.graal-java-version }})"
      if: ${{ inputs.graal-java-version != '' }}
      uses: graalvm/setup-graalvm@main
      with:
        java-version: ${{ inputs.graal-java-version }}
        distribution: 'graalvm'
        github-token: ${{ inputs.github-token }}
        set-java-home: 'false'
    - name: "🔒 Configure push access"
      if: ${{ inputs.push-access == '1' }}
      shell: "bash"
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        GIT_SSH: "ssh"
        SSH_PRIVATE_KEY: "${{ inputs.ssh-key }}"
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 700 -R ~/.ssh
        ssh-keygen -p -f ~/.ssh/id_rsa -m pem
        eval "$(ssh-agent -s)"
        ssh-add
        ssh git@github.com || true
        git config --global user.name 'graalvm bot'
        git config --global user.email 'graalvmbot@users.noreply.github.com'
        echo "org.ajoberstar.grgit.auth.command.allow=true" >> gradle.properties
