name: junit-platform-native-feature

on:
  push:
    paths:
      - 'common/junit-platform-native/**'
  pull_request:
    paths:
      - 'common/junit-platform-native/**'
  workflow_dispatch:

jobs:
  test-junit-platform-native-feature:
    name:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Get GraalVM Nightly
        run: |
          source common/scripts/downloadGraalVM.sh
          echo "$GRAALVM_HOME/bin" >> $GITHUB_PATH
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "GRAALVM_HOME=$GRAALVM_HOME" >> $GITHUB_ENV
      - name: Checkstyle
        run: ./gradlew :junit-platform-native:checkstyleMain :junit-platform-native:checkstyleTest
      - name: JVM test
        run: ./gradlew :junit-platform-native:test
      - name: Feature test
        run: ./gradlew :junit-platform-native:nativeTest
      - name: Tests results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: tests-results
          path: common/junit-platform-native/build/reports/tests/
