name: native-maven-plugin

on:
  push:
    paths:
      - 'native-maven-plugin/**'
      - 'samples/**'
      - 'common/**'
  pull_request:
    paths:
      - 'native-maven-plugin/**'
      - 'samples/**'
      - 'common/**'
  workflow_dispatch: [ ]

jobs:
  test-native-maven-plugin:
    name:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Check and test the plugin
        run: |
          pushd native-maven-plugin
            ./gradlew check --no-daemon
          popd
