{
  "formatVersion": "1.1",
  "component": {
    "group": "org.graalvm.buildtools",
    "module": "native-maven-plugin",
    "version": "0.10.7-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "native-maven-plugin-0.10.7-SNAPSHOT.jar",
          "url": "native-maven-plugin-0.10.7-SNAPSHOT.jar",
          "size": 112720,
          "sha512": "a17dbf9497254ad5c6c0d129c53aa5eefc7e47c96fdb93a81ea36010f0fa49fd5b6f9931805ed20d3ec01b56e75e63aa966c501c519648253bd9d99e8fabaf51",
          "sha256": "0ac08900931f78e2a7a8b9e17341f31b766a8a82d3c4aa72a1782c13776deb6a",
          "sha1": "52a2c460048b4ef7602e2f50a454e1866abb2ff8",
          "md5": "f1490ba34695685a8d74f69914b67224"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.graalvm.buildtools",
          "module": "utils",
          "version": {
            "requires": "0.10.7-SNAPSHOT"
          }
        },
        {
          "group": "com.github.openjson",
          "module": "openjson",
          "version": {
            "requires": "1.0.13"
          }
        },
        {
          "group": "org.graalvm.buildtools",
          "module": "graalvm-reachability-metadata",
          "version": {
            "requires": "0.10.7-SNAPSHOT"
          }
        },
        {
          "group": "org.cyclonedx",
          "module": "cyclonedx-maven-plugin",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.twdata.maven",
          "module": "mojo-executor",
          "version": {
            "requires": "2.4.1"
          }
        }
      ],
      "files": [
        {
          "name": "native-maven-plugin-0.10.7-SNAPSHOT.jar",
          "url": "native-maven-plugin-0.10.7-SNAPSHOT.jar",
          "size": 112720,
          "sha512": "a17dbf9497254ad5c6c0d129c53aa5eefc7e47c96fdb93a81ea36010f0fa49fd5b6f9931805ed20d3ec01b56e75e63aa966c501c519648253bd9d99e8fabaf51",
          "sha256": "0ac08900931f78e2a7a8b9e17341f31b766a8a82d3c4aa72a1782c13776deb6a",
          "sha1": "52a2c460048b4ef7602e2f50a454e1866abb2ff8",
          "md5": "f1490ba34695685a8d74f69914b67224"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-maven-plugin-0.10.7-SNAPSHOT-javadoc.jar",
          "url": "native-maven-plugin-0.10.7-SNAPSHOT-javadoc.jar",
          "size": 426463,
          "sha512": "b952022be5fdb4314a2ab8ab508ad885d9c730f7275f5c20a07b719320c0ac8798d91537c1ebba60a388ea30f23ecc38cceba579a34e53e392d67b8dabc24c42",
          "sha256": "2ce67a6ba13beccdfc2af25b91aa7a4e28061cff55051b50ff1285a057810c40",
          "sha1": "385987209870b4aef7f3e5653ace4d4d3deb2f8a",
          "md5": "288c330fa938ac64a6cebaac8e68c2d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "native-maven-plugin-0.10.7-SNAPSHOT-sources.jar",
          "url": "native-maven-plugin-0.10.7-SNAPSHOT-sources.jar",
          "size": 84559,
          "sha512": "54ae7cf706fb429dc201a240ac086966c00b7745f0a399d4a5492251b612b899c3fc36840e3b7e1ddf01d9e622ae486edf310bb2a68debbfcbddfc369f57e801",
          "sha256": "c924ea810b3ce4b51c4be838633f2acb1de8d3e545d550a699995f7e84a39d23",
          "sha1": "96b7f8eba4910a984b00dd250ffac148193916c0",
          "md5": "ab07fc8ff6ce9e33dde280dee93cc27b"
        }
      ]
    }
  ]
}
